// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emfinancialindicator"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emstockbasicinfo"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emstockwatch"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/predicate"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The EmFinancialIndicatorFunc type is an adapter to allow the use of ordinary function as a Querier.
type EmFinancialIndicatorFunc func(context.Context, *ent.EmFinancialIndicatorQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f EmFinancialIndicatorFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.EmFinancialIndicatorQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.EmFinancialIndicatorQuery", q)
}

// The TraverseEmFinancialIndicator type is an adapter to allow the use of ordinary function as Traverser.
type TraverseEmFinancialIndicator func(context.Context, *ent.EmFinancialIndicatorQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseEmFinancialIndicator) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseEmFinancialIndicator) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.EmFinancialIndicatorQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.EmFinancialIndicatorQuery", q)
}

// The EmStockBasicInfoFunc type is an adapter to allow the use of ordinary function as a Querier.
type EmStockBasicInfoFunc func(context.Context, *ent.EmStockBasicInfoQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f EmStockBasicInfoFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.EmStockBasicInfoQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.EmStockBasicInfoQuery", q)
}

// The TraverseEmStockBasicInfo type is an adapter to allow the use of ordinary function as Traverser.
type TraverseEmStockBasicInfo func(context.Context, *ent.EmStockBasicInfoQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseEmStockBasicInfo) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseEmStockBasicInfo) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.EmStockBasicInfoQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.EmStockBasicInfoQuery", q)
}

// The EmStockWatchFunc type is an adapter to allow the use of ordinary function as a Querier.
type EmStockWatchFunc func(context.Context, *ent.EmStockWatchQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f EmStockWatchFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.EmStockWatchQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.EmStockWatchQuery", q)
}

// The TraverseEmStockWatch type is an adapter to allow the use of ordinary function as Traverser.
type TraverseEmStockWatch func(context.Context, *ent.EmStockWatchQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseEmStockWatch) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseEmStockWatch) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.EmStockWatchQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.EmStockWatchQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.EmFinancialIndicatorQuery:
		return &query[*ent.EmFinancialIndicatorQuery, predicate.EmFinancialIndicator, emfinancialindicator.OrderOption]{typ: ent.TypeEmFinancialIndicator, tq: q}, nil
	case *ent.EmStockBasicInfoQuery:
		return &query[*ent.EmStockBasicInfoQuery, predicate.EmStockBasicInfo, emstockbasicinfo.OrderOption]{typ: ent.TypeEmStockBasicInfo, tq: q}, nil
	case *ent.EmStockWatchQuery:
		return &query[*ent.EmStockWatchQuery, predicate.EmStockWatch, emstockwatch.OrderOption]{typ: ent.TypeEmStockWatch, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
