// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// EmFinancialIndicator is the predicate function for emfinancialindicator builders.
type EmFinancialIndicator func(*sql.Selector)

// EmStockBasicInfo is the predicate function for emstockbasicinfo builders.
type EmStockBasicInfo func(*sql.Selector)

// EmStockWatch is the predicate function for emstockwatch builders.
type EmStockWatch func(*sql.Selector)
