// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/suyuan32/simple-admin-efinance-rpc/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emfinancialindicator"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emstockbasicinfo"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emstockwatch"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// EmFinancialIndicator is the client for interacting with the EmFinancialIndicator builders.
	EmFinancialIndicator *EmFinancialIndicatorClient
	// EmStockBasicInfo is the client for interacting with the EmStockBasicInfo builders.
	EmStockBasicInfo *EmStockBasicInfoClient
	// EmStockWatch is the client for interacting with the EmStockWatch builders.
	EmStockWatch *EmStockWatchClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.EmFinancialIndicator = NewEmFinancialIndicatorClient(c.config)
	c.EmStockBasicInfo = NewEmStockBasicInfoClient(c.config)
	c.EmStockWatch = NewEmStockWatchClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		EmFinancialIndicator: NewEmFinancialIndicatorClient(cfg),
		EmStockBasicInfo:     NewEmStockBasicInfoClient(cfg),
		EmStockWatch:         NewEmStockWatchClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		EmFinancialIndicator: NewEmFinancialIndicatorClient(cfg),
		EmStockBasicInfo:     NewEmStockBasicInfoClient(cfg),
		EmStockWatch:         NewEmStockWatchClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		EmFinancialIndicator.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.EmFinancialIndicator.Use(hooks...)
	c.EmStockBasicInfo.Use(hooks...)
	c.EmStockWatch.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.EmFinancialIndicator.Intercept(interceptors...)
	c.EmStockBasicInfo.Intercept(interceptors...)
	c.EmStockWatch.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *EmFinancialIndicatorMutation:
		return c.EmFinancialIndicator.mutate(ctx, m)
	case *EmStockBasicInfoMutation:
		return c.EmStockBasicInfo.mutate(ctx, m)
	case *EmStockWatchMutation:
		return c.EmStockWatch.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// EmFinancialIndicatorClient is a client for the EmFinancialIndicator schema.
type EmFinancialIndicatorClient struct {
	config
}

// NewEmFinancialIndicatorClient returns a client for the EmFinancialIndicator from the given config.
func NewEmFinancialIndicatorClient(c config) *EmFinancialIndicatorClient {
	return &EmFinancialIndicatorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `emfinancialindicator.Hooks(f(g(h())))`.
func (c *EmFinancialIndicatorClient) Use(hooks ...Hook) {
	c.hooks.EmFinancialIndicator = append(c.hooks.EmFinancialIndicator, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `emfinancialindicator.Intercept(f(g(h())))`.
func (c *EmFinancialIndicatorClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmFinancialIndicator = append(c.inters.EmFinancialIndicator, interceptors...)
}

// Create returns a builder for creating a EmFinancialIndicator entity.
func (c *EmFinancialIndicatorClient) Create() *EmFinancialIndicatorCreate {
	mutation := newEmFinancialIndicatorMutation(c.config, OpCreate)
	return &EmFinancialIndicatorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmFinancialIndicator entities.
func (c *EmFinancialIndicatorClient) CreateBulk(builders ...*EmFinancialIndicatorCreate) *EmFinancialIndicatorCreateBulk {
	return &EmFinancialIndicatorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmFinancialIndicatorClient) MapCreateBulk(slice any, setFunc func(*EmFinancialIndicatorCreate, int)) *EmFinancialIndicatorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmFinancialIndicatorCreateBulk{err: fmt.Errorf("calling to EmFinancialIndicatorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmFinancialIndicatorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmFinancialIndicatorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmFinancialIndicator.
func (c *EmFinancialIndicatorClient) Update() *EmFinancialIndicatorUpdate {
	mutation := newEmFinancialIndicatorMutation(c.config, OpUpdate)
	return &EmFinancialIndicatorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmFinancialIndicatorClient) UpdateOne(efi *EmFinancialIndicator) *EmFinancialIndicatorUpdateOne {
	mutation := newEmFinancialIndicatorMutation(c.config, OpUpdateOne, withEmFinancialIndicator(efi))
	return &EmFinancialIndicatorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmFinancialIndicatorClient) UpdateOneID(id int32) *EmFinancialIndicatorUpdateOne {
	mutation := newEmFinancialIndicatorMutation(c.config, OpUpdateOne, withEmFinancialIndicatorID(id))
	return &EmFinancialIndicatorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmFinancialIndicator.
func (c *EmFinancialIndicatorClient) Delete() *EmFinancialIndicatorDelete {
	mutation := newEmFinancialIndicatorMutation(c.config, OpDelete)
	return &EmFinancialIndicatorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmFinancialIndicatorClient) DeleteOne(efi *EmFinancialIndicator) *EmFinancialIndicatorDeleteOne {
	return c.DeleteOneID(efi.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmFinancialIndicatorClient) DeleteOneID(id int32) *EmFinancialIndicatorDeleteOne {
	builder := c.Delete().Where(emfinancialindicator.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmFinancialIndicatorDeleteOne{builder}
}

// Query returns a query builder for EmFinancialIndicator.
func (c *EmFinancialIndicatorClient) Query() *EmFinancialIndicatorQuery {
	return &EmFinancialIndicatorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmFinancialIndicator},
		inters: c.Interceptors(),
	}
}

// Get returns a EmFinancialIndicator entity by its id.
func (c *EmFinancialIndicatorClient) Get(ctx context.Context, id int32) (*EmFinancialIndicator, error) {
	return c.Query().Where(emfinancialindicator.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmFinancialIndicatorClient) GetX(ctx context.Context, id int32) *EmFinancialIndicator {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EmFinancialIndicatorClient) Hooks() []Hook {
	return c.hooks.EmFinancialIndicator
}

// Interceptors returns the client interceptors.
func (c *EmFinancialIndicatorClient) Interceptors() []Interceptor {
	return c.inters.EmFinancialIndicator
}

func (c *EmFinancialIndicatorClient) mutate(ctx context.Context, m *EmFinancialIndicatorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmFinancialIndicatorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmFinancialIndicatorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmFinancialIndicatorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmFinancialIndicatorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmFinancialIndicator mutation op: %q", m.Op())
	}
}

// EmStockBasicInfoClient is a client for the EmStockBasicInfo schema.
type EmStockBasicInfoClient struct {
	config
}

// NewEmStockBasicInfoClient returns a client for the EmStockBasicInfo from the given config.
func NewEmStockBasicInfoClient(c config) *EmStockBasicInfoClient {
	return &EmStockBasicInfoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `emstockbasicinfo.Hooks(f(g(h())))`.
func (c *EmStockBasicInfoClient) Use(hooks ...Hook) {
	c.hooks.EmStockBasicInfo = append(c.hooks.EmStockBasicInfo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `emstockbasicinfo.Intercept(f(g(h())))`.
func (c *EmStockBasicInfoClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmStockBasicInfo = append(c.inters.EmStockBasicInfo, interceptors...)
}

// Create returns a builder for creating a EmStockBasicInfo entity.
func (c *EmStockBasicInfoClient) Create() *EmStockBasicInfoCreate {
	mutation := newEmStockBasicInfoMutation(c.config, OpCreate)
	return &EmStockBasicInfoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmStockBasicInfo entities.
func (c *EmStockBasicInfoClient) CreateBulk(builders ...*EmStockBasicInfoCreate) *EmStockBasicInfoCreateBulk {
	return &EmStockBasicInfoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmStockBasicInfoClient) MapCreateBulk(slice any, setFunc func(*EmStockBasicInfoCreate, int)) *EmStockBasicInfoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmStockBasicInfoCreateBulk{err: fmt.Errorf("calling to EmStockBasicInfoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmStockBasicInfoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmStockBasicInfoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmStockBasicInfo.
func (c *EmStockBasicInfoClient) Update() *EmStockBasicInfoUpdate {
	mutation := newEmStockBasicInfoMutation(c.config, OpUpdate)
	return &EmStockBasicInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmStockBasicInfoClient) UpdateOne(esbi *EmStockBasicInfo) *EmStockBasicInfoUpdateOne {
	mutation := newEmStockBasicInfoMutation(c.config, OpUpdateOne, withEmStockBasicInfo(esbi))
	return &EmStockBasicInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmStockBasicInfoClient) UpdateOneID(id int32) *EmStockBasicInfoUpdateOne {
	mutation := newEmStockBasicInfoMutation(c.config, OpUpdateOne, withEmStockBasicInfoID(id))
	return &EmStockBasicInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmStockBasicInfo.
func (c *EmStockBasicInfoClient) Delete() *EmStockBasicInfoDelete {
	mutation := newEmStockBasicInfoMutation(c.config, OpDelete)
	return &EmStockBasicInfoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmStockBasicInfoClient) DeleteOne(esbi *EmStockBasicInfo) *EmStockBasicInfoDeleteOne {
	return c.DeleteOneID(esbi.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmStockBasicInfoClient) DeleteOneID(id int32) *EmStockBasicInfoDeleteOne {
	builder := c.Delete().Where(emstockbasicinfo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmStockBasicInfoDeleteOne{builder}
}

// Query returns a query builder for EmStockBasicInfo.
func (c *EmStockBasicInfoClient) Query() *EmStockBasicInfoQuery {
	return &EmStockBasicInfoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmStockBasicInfo},
		inters: c.Interceptors(),
	}
}

// Get returns a EmStockBasicInfo entity by its id.
func (c *EmStockBasicInfoClient) Get(ctx context.Context, id int32) (*EmStockBasicInfo, error) {
	return c.Query().Where(emstockbasicinfo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmStockBasicInfoClient) GetX(ctx context.Context, id int32) *EmStockBasicInfo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EmStockBasicInfoClient) Hooks() []Hook {
	return c.hooks.EmStockBasicInfo
}

// Interceptors returns the client interceptors.
func (c *EmStockBasicInfoClient) Interceptors() []Interceptor {
	return c.inters.EmStockBasicInfo
}

func (c *EmStockBasicInfoClient) mutate(ctx context.Context, m *EmStockBasicInfoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmStockBasicInfoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmStockBasicInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmStockBasicInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmStockBasicInfoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmStockBasicInfo mutation op: %q", m.Op())
	}
}

// EmStockWatchClient is a client for the EmStockWatch schema.
type EmStockWatchClient struct {
	config
}

// NewEmStockWatchClient returns a client for the EmStockWatch from the given config.
func NewEmStockWatchClient(c config) *EmStockWatchClient {
	return &EmStockWatchClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `emstockwatch.Hooks(f(g(h())))`.
func (c *EmStockWatchClient) Use(hooks ...Hook) {
	c.hooks.EmStockWatch = append(c.hooks.EmStockWatch, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `emstockwatch.Intercept(f(g(h())))`.
func (c *EmStockWatchClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmStockWatch = append(c.inters.EmStockWatch, interceptors...)
}

// Create returns a builder for creating a EmStockWatch entity.
func (c *EmStockWatchClient) Create() *EmStockWatchCreate {
	mutation := newEmStockWatchMutation(c.config, OpCreate)
	return &EmStockWatchCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmStockWatch entities.
func (c *EmStockWatchClient) CreateBulk(builders ...*EmStockWatchCreate) *EmStockWatchCreateBulk {
	return &EmStockWatchCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmStockWatchClient) MapCreateBulk(slice any, setFunc func(*EmStockWatchCreate, int)) *EmStockWatchCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmStockWatchCreateBulk{err: fmt.Errorf("calling to EmStockWatchClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmStockWatchCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmStockWatchCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmStockWatch.
func (c *EmStockWatchClient) Update() *EmStockWatchUpdate {
	mutation := newEmStockWatchMutation(c.config, OpUpdate)
	return &EmStockWatchUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmStockWatchClient) UpdateOne(esw *EmStockWatch) *EmStockWatchUpdateOne {
	mutation := newEmStockWatchMutation(c.config, OpUpdateOne, withEmStockWatch(esw))
	return &EmStockWatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmStockWatchClient) UpdateOneID(id int32) *EmStockWatchUpdateOne {
	mutation := newEmStockWatchMutation(c.config, OpUpdateOne, withEmStockWatchID(id))
	return &EmStockWatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmStockWatch.
func (c *EmStockWatchClient) Delete() *EmStockWatchDelete {
	mutation := newEmStockWatchMutation(c.config, OpDelete)
	return &EmStockWatchDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmStockWatchClient) DeleteOne(esw *EmStockWatch) *EmStockWatchDeleteOne {
	return c.DeleteOneID(esw.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmStockWatchClient) DeleteOneID(id int32) *EmStockWatchDeleteOne {
	builder := c.Delete().Where(emstockwatch.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmStockWatchDeleteOne{builder}
}

// Query returns a query builder for EmStockWatch.
func (c *EmStockWatchClient) Query() *EmStockWatchQuery {
	return &EmStockWatchQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmStockWatch},
		inters: c.Interceptors(),
	}
}

// Get returns a EmStockWatch entity by its id.
func (c *EmStockWatchClient) Get(ctx context.Context, id int32) (*EmStockWatch, error) {
	return c.Query().Where(emstockwatch.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmStockWatchClient) GetX(ctx context.Context, id int32) *EmStockWatch {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EmStockWatchClient) Hooks() []Hook {
	return c.hooks.EmStockWatch
}

// Interceptors returns the client interceptors.
func (c *EmStockWatchClient) Interceptors() []Interceptor {
	return c.inters.EmStockWatch
}

func (c *EmStockWatchClient) mutate(ctx context.Context, m *EmStockWatchMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmStockWatchCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmStockWatchUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmStockWatchUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmStockWatchDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmStockWatch mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		EmFinancialIndicator, EmStockBasicInfo, EmStockWatch []ent.Hook
	}
	inters struct {
		EmFinancialIndicator, EmStockBasicInfo, EmStockWatch []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
