// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emfinancialindicator"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/predicate"
)

// EmFinancialIndicatorQuery is the builder for querying EmFinancialIndicator entities.
type EmFinancialIndicatorQuery struct {
	config
	ctx        *QueryContext
	order      []emfinancialindicator.OrderOption
	inters     []Interceptor
	predicates []predicate.EmFinancialIndicator
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EmFinancialIndicatorQuery builder.
func (efiq *EmFinancialIndicatorQuery) Where(ps ...predicate.EmFinancialIndicator) *EmFinancialIndicatorQuery {
	efiq.predicates = append(efiq.predicates, ps...)
	return efiq
}

// Limit the number of records to be returned by this query.
func (efiq *EmFinancialIndicatorQuery) Limit(limit int) *EmFinancialIndicatorQuery {
	efiq.ctx.Limit = &limit
	return efiq
}

// Offset to start from.
func (efiq *EmFinancialIndicatorQuery) Offset(offset int) *EmFinancialIndicatorQuery {
	efiq.ctx.Offset = &offset
	return efiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (efiq *EmFinancialIndicatorQuery) Unique(unique bool) *EmFinancialIndicatorQuery {
	efiq.ctx.Unique = &unique
	return efiq
}

// Order specifies how the records should be ordered.
func (efiq *EmFinancialIndicatorQuery) Order(o ...emfinancialindicator.OrderOption) *EmFinancialIndicatorQuery {
	efiq.order = append(efiq.order, o...)
	return efiq
}

// First returns the first EmFinancialIndicator entity from the query.
// Returns a *NotFoundError when no EmFinancialIndicator was found.
func (efiq *EmFinancialIndicatorQuery) First(ctx context.Context) (*EmFinancialIndicator, error) {
	nodes, err := efiq.Limit(1).All(setContextOp(ctx, efiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{emfinancialindicator.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (efiq *EmFinancialIndicatorQuery) FirstX(ctx context.Context) *EmFinancialIndicator {
	node, err := efiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EmFinancialIndicator ID from the query.
// Returns a *NotFoundError when no EmFinancialIndicator ID was found.
func (efiq *EmFinancialIndicatorQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = efiq.Limit(1).IDs(setContextOp(ctx, efiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{emfinancialindicator.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (efiq *EmFinancialIndicatorQuery) FirstIDX(ctx context.Context) int32 {
	id, err := efiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EmFinancialIndicator entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EmFinancialIndicator entity is found.
// Returns a *NotFoundError when no EmFinancialIndicator entities are found.
func (efiq *EmFinancialIndicatorQuery) Only(ctx context.Context) (*EmFinancialIndicator, error) {
	nodes, err := efiq.Limit(2).All(setContextOp(ctx, efiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{emfinancialindicator.Label}
	default:
		return nil, &NotSingularError{emfinancialindicator.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (efiq *EmFinancialIndicatorQuery) OnlyX(ctx context.Context) *EmFinancialIndicator {
	node, err := efiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EmFinancialIndicator ID in the query.
// Returns a *NotSingularError when more than one EmFinancialIndicator ID is found.
// Returns a *NotFoundError when no entities are found.
func (efiq *EmFinancialIndicatorQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = efiq.Limit(2).IDs(setContextOp(ctx, efiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{emfinancialindicator.Label}
	default:
		err = &NotSingularError{emfinancialindicator.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (efiq *EmFinancialIndicatorQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := efiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EmFinancialIndicators.
func (efiq *EmFinancialIndicatorQuery) All(ctx context.Context) ([]*EmFinancialIndicator, error) {
	ctx = setContextOp(ctx, efiq.ctx, ent.OpQueryAll)
	if err := efiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EmFinancialIndicator, *EmFinancialIndicatorQuery]()
	return withInterceptors[[]*EmFinancialIndicator](ctx, efiq, qr, efiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (efiq *EmFinancialIndicatorQuery) AllX(ctx context.Context) []*EmFinancialIndicator {
	nodes, err := efiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EmFinancialIndicator IDs.
func (efiq *EmFinancialIndicatorQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if efiq.ctx.Unique == nil && efiq.path != nil {
		efiq.Unique(true)
	}
	ctx = setContextOp(ctx, efiq.ctx, ent.OpQueryIDs)
	if err = efiq.Select(emfinancialindicator.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (efiq *EmFinancialIndicatorQuery) IDsX(ctx context.Context) []int32 {
	ids, err := efiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (efiq *EmFinancialIndicatorQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, efiq.ctx, ent.OpQueryCount)
	if err := efiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, efiq, querierCount[*EmFinancialIndicatorQuery](), efiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (efiq *EmFinancialIndicatorQuery) CountX(ctx context.Context) int {
	count, err := efiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (efiq *EmFinancialIndicatorQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, efiq.ctx, ent.OpQueryExist)
	switch _, err := efiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (efiq *EmFinancialIndicatorQuery) ExistX(ctx context.Context) bool {
	exist, err := efiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EmFinancialIndicatorQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (efiq *EmFinancialIndicatorQuery) Clone() *EmFinancialIndicatorQuery {
	if efiq == nil {
		return nil
	}
	return &EmFinancialIndicatorQuery{
		config:     efiq.config,
		ctx:        efiq.ctx.Clone(),
		order:      append([]emfinancialindicator.OrderOption{}, efiq.order...),
		inters:     append([]Interceptor{}, efiq.inters...),
		predicates: append([]predicate.EmFinancialIndicator{}, efiq.predicates...),
		// clone intermediate query.
		sql:  efiq.sql.Clone(),
		path: efiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FinancialIndicatorsKey string `json:"financial_indicators_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EmFinancialIndicator.Query().
//		GroupBy(emfinancialindicator.FieldFinancialIndicatorsKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (efiq *EmFinancialIndicatorQuery) GroupBy(field string, fields ...string) *EmFinancialIndicatorGroupBy {
	efiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EmFinancialIndicatorGroupBy{build: efiq}
	grbuild.flds = &efiq.ctx.Fields
	grbuild.label = emfinancialindicator.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FinancialIndicatorsKey string `json:"financial_indicators_key,omitempty"`
//	}
//
//	client.EmFinancialIndicator.Query().
//		Select(emfinancialindicator.FieldFinancialIndicatorsKey).
//		Scan(ctx, &v)
func (efiq *EmFinancialIndicatorQuery) Select(fields ...string) *EmFinancialIndicatorSelect {
	efiq.ctx.Fields = append(efiq.ctx.Fields, fields...)
	sbuild := &EmFinancialIndicatorSelect{EmFinancialIndicatorQuery: efiq}
	sbuild.label = emfinancialindicator.Label
	sbuild.flds, sbuild.scan = &efiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EmFinancialIndicatorSelect configured with the given aggregations.
func (efiq *EmFinancialIndicatorQuery) Aggregate(fns ...AggregateFunc) *EmFinancialIndicatorSelect {
	return efiq.Select().Aggregate(fns...)
}

func (efiq *EmFinancialIndicatorQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range efiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, efiq); err != nil {
				return err
			}
		}
	}
	for _, f := range efiq.ctx.Fields {
		if !emfinancialindicator.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if efiq.path != nil {
		prev, err := efiq.path(ctx)
		if err != nil {
			return err
		}
		efiq.sql = prev
	}
	return nil
}

func (efiq *EmFinancialIndicatorQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EmFinancialIndicator, error) {
	var (
		nodes = []*EmFinancialIndicator{}
		_spec = efiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EmFinancialIndicator).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EmFinancialIndicator{config: efiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, efiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (efiq *EmFinancialIndicatorQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := efiq.querySpec()
	_spec.Node.Columns = efiq.ctx.Fields
	if len(efiq.ctx.Fields) > 0 {
		_spec.Unique = efiq.ctx.Unique != nil && *efiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, efiq.driver, _spec)
}

func (efiq *EmFinancialIndicatorQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(emfinancialindicator.Table, emfinancialindicator.Columns, sqlgraph.NewFieldSpec(emfinancialindicator.FieldID, field.TypeInt32))
	_spec.From = efiq.sql
	if unique := efiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if efiq.path != nil {
		_spec.Unique = true
	}
	if fields := efiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emfinancialindicator.FieldID)
		for i := range fields {
			if fields[i] != emfinancialindicator.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := efiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := efiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := efiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := efiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (efiq *EmFinancialIndicatorQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(efiq.driver.Dialect())
	t1 := builder.Table(emfinancialindicator.Table)
	columns := efiq.ctx.Fields
	if len(columns) == 0 {
		columns = emfinancialindicator.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if efiq.sql != nil {
		selector = efiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if efiq.ctx.Unique != nil && *efiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range efiq.predicates {
		p(selector)
	}
	for _, p := range efiq.order {
		p(selector)
	}
	if offset := efiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := efiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EmFinancialIndicatorGroupBy is the group-by builder for EmFinancialIndicator entities.
type EmFinancialIndicatorGroupBy struct {
	selector
	build *EmFinancialIndicatorQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (efigb *EmFinancialIndicatorGroupBy) Aggregate(fns ...AggregateFunc) *EmFinancialIndicatorGroupBy {
	efigb.fns = append(efigb.fns, fns...)
	return efigb
}

// Scan applies the selector query and scans the result into the given value.
func (efigb *EmFinancialIndicatorGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, efigb.build.ctx, ent.OpQueryGroupBy)
	if err := efigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmFinancialIndicatorQuery, *EmFinancialIndicatorGroupBy](ctx, efigb.build, efigb, efigb.build.inters, v)
}

func (efigb *EmFinancialIndicatorGroupBy) sqlScan(ctx context.Context, root *EmFinancialIndicatorQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(efigb.fns))
	for _, fn := range efigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*efigb.flds)+len(efigb.fns))
		for _, f := range *efigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*efigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := efigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EmFinancialIndicatorSelect is the builder for selecting fields of EmFinancialIndicator entities.
type EmFinancialIndicatorSelect struct {
	*EmFinancialIndicatorQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (efis *EmFinancialIndicatorSelect) Aggregate(fns ...AggregateFunc) *EmFinancialIndicatorSelect {
	efis.fns = append(efis.fns, fns...)
	return efis
}

// Scan applies the selector query and scans the result into the given value.
func (efis *EmFinancialIndicatorSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, efis.ctx, ent.OpQuerySelect)
	if err := efis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmFinancialIndicatorQuery, *EmFinancialIndicatorSelect](ctx, efis.EmFinancialIndicatorQuery, efis, efis.inters, v)
}

func (efis *EmFinancialIndicatorSelect) sqlScan(ctx context.Context, root *EmFinancialIndicatorQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(efis.fns))
	for _, fn := range efis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*efis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := efis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
