// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emfinancialindicator"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/predicate"
)

// EmFinancialIndicatorDelete is the builder for deleting a EmFinancialIndicator entity.
type EmFinancialIndicatorDelete struct {
	config
	hooks    []Hook
	mutation *EmFinancialIndicatorMutation
}

// Where appends a list predicates to the EmFinancialIndicatorDelete builder.
func (efid *EmFinancialIndicatorDelete) Where(ps ...predicate.EmFinancialIndicator) *EmFinancialIndicatorDelete {
	efid.mutation.Where(ps...)
	return efid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (efid *EmFinancialIndicatorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, efid.sqlExec, efid.mutation, efid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (efid *EmFinancialIndicatorDelete) ExecX(ctx context.Context) int {
	n, err := efid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (efid *EmFinancialIndicatorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(emfinancialindicator.Table, sqlgraph.NewFieldSpec(emfinancialindicator.FieldID, field.TypeInt32))
	if ps := efid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, efid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	efid.mutation.done = true
	return affected, err
}

// EmFinancialIndicatorDeleteOne is the builder for deleting a single EmFinancialIndicator entity.
type EmFinancialIndicatorDeleteOne struct {
	efid *EmFinancialIndicatorDelete
}

// Where appends a list predicates to the EmFinancialIndicatorDelete builder.
func (efido *EmFinancialIndicatorDeleteOne) Where(ps ...predicate.EmFinancialIndicator) *EmFinancialIndicatorDeleteOne {
	efido.efid.mutation.Where(ps...)
	return efido
}

// Exec executes the deletion query.
func (efido *EmFinancialIndicatorDeleteOne) Exec(ctx context.Context) error {
	n, err := efido.efid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{emfinancialindicator.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (efido *EmFinancialIndicatorDeleteOne) ExecX(ctx context.Context) {
	if err := efido.Exec(ctx); err != nil {
		panic(err)
	}
}
