// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emstockbasicinfo"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/predicate"
)

// EmStockBasicInfoUpdate is the builder for updating EmStockBasicInfo entities.
type EmStockBasicInfoUpdate struct {
	config
	hooks    []Hook
	mutation *EmStockBasicInfoMutation
}

// Where appends a list predicates to the EmStockBasicInfoUpdate builder.
func (esbiu *EmStockBasicInfoUpdate) Where(ps ...predicate.EmStockBasicInfo) *EmStockBasicInfoUpdate {
	esbiu.mutation.Where(ps...)
	return esbiu
}

// SetF1 sets the "f1" field.
func (esbiu *EmStockBasicInfoUpdate) SetF1(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF1(s)
	return esbiu
}

// SetNillableF1 sets the "f1" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF1(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF1(*s)
	}
	return esbiu
}

// ClearF1 clears the value of the "f1" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF1() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF1()
	return esbiu
}

// SetF2 sets the "f2" field.
func (esbiu *EmStockBasicInfoUpdate) SetF2(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF2(s)
	return esbiu
}

// SetNillableF2 sets the "f2" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF2(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF2(*s)
	}
	return esbiu
}

// ClearF2 clears the value of the "f2" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF2() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF2()
	return esbiu
}

// SetF3 sets the "f3" field.
func (esbiu *EmStockBasicInfoUpdate) SetF3(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF3(s)
	return esbiu
}

// SetNillableF3 sets the "f3" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF3(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF3(*s)
	}
	return esbiu
}

// ClearF3 clears the value of the "f3" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF3() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF3()
	return esbiu
}

// SetF4 sets the "f4" field.
func (esbiu *EmStockBasicInfoUpdate) SetF4(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF4(s)
	return esbiu
}

// SetNillableF4 sets the "f4" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF4(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF4(*s)
	}
	return esbiu
}

// ClearF4 clears the value of the "f4" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF4() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF4()
	return esbiu
}

// SetF5 sets the "f5" field.
func (esbiu *EmStockBasicInfoUpdate) SetF5(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF5(s)
	return esbiu
}

// SetNillableF5 sets the "f5" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF5(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF5(*s)
	}
	return esbiu
}

// ClearF5 clears the value of the "f5" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF5() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF5()
	return esbiu
}

// SetF6 sets the "f6" field.
func (esbiu *EmStockBasicInfoUpdate) SetF6(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF6(s)
	return esbiu
}

// SetNillableF6 sets the "f6" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF6(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF6(*s)
	}
	return esbiu
}

// ClearF6 clears the value of the "f6" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF6() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF6()
	return esbiu
}

// SetF7 sets the "f7" field.
func (esbiu *EmStockBasicInfoUpdate) SetF7(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF7(s)
	return esbiu
}

// SetNillableF7 sets the "f7" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF7(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF7(*s)
	}
	return esbiu
}

// ClearF7 clears the value of the "f7" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF7() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF7()
	return esbiu
}

// SetF8 sets the "f8" field.
func (esbiu *EmStockBasicInfoUpdate) SetF8(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF8(s)
	return esbiu
}

// SetNillableF8 sets the "f8" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF8(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF8(*s)
	}
	return esbiu
}

// ClearF8 clears the value of the "f8" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF8() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF8()
	return esbiu
}

// SetF9 sets the "f9" field.
func (esbiu *EmStockBasicInfoUpdate) SetF9(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF9(s)
	return esbiu
}

// SetNillableF9 sets the "f9" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF9(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF9(*s)
	}
	return esbiu
}

// ClearF9 clears the value of the "f9" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF9() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF9()
	return esbiu
}

// SetF10 sets the "f10" field.
func (esbiu *EmStockBasicInfoUpdate) SetF10(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF10(s)
	return esbiu
}

// SetNillableF10 sets the "f10" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF10(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF10(*s)
	}
	return esbiu
}

// ClearF10 clears the value of the "f10" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF10() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF10()
	return esbiu
}

// SetF11 sets the "f11" field.
func (esbiu *EmStockBasicInfoUpdate) SetF11(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF11(s)
	return esbiu
}

// SetNillableF11 sets the "f11" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF11(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF11(*s)
	}
	return esbiu
}

// ClearF11 clears the value of the "f11" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF11() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF11()
	return esbiu
}

// SetF12 sets the "f12" field.
func (esbiu *EmStockBasicInfoUpdate) SetF12(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF12(s)
	return esbiu
}

// SetNillableF12 sets the "f12" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF12(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF12(*s)
	}
	return esbiu
}

// ClearF12 clears the value of the "f12" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF12() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF12()
	return esbiu
}

// SetF13 sets the "f13" field.
func (esbiu *EmStockBasicInfoUpdate) SetF13(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF13(s)
	return esbiu
}

// SetNillableF13 sets the "f13" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF13(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF13(*s)
	}
	return esbiu
}

// ClearF13 clears the value of the "f13" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF13() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF13()
	return esbiu
}

// SetF14 sets the "f14" field.
func (esbiu *EmStockBasicInfoUpdate) SetF14(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF14(s)
	return esbiu
}

// SetNillableF14 sets the "f14" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF14(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF14(*s)
	}
	return esbiu
}

// ClearF14 clears the value of the "f14" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF14() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF14()
	return esbiu
}

// SetF15 sets the "f15" field.
func (esbiu *EmStockBasicInfoUpdate) SetF15(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF15(s)
	return esbiu
}

// SetNillableF15 sets the "f15" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF15(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF15(*s)
	}
	return esbiu
}

// ClearF15 clears the value of the "f15" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF15() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF15()
	return esbiu
}

// SetF16 sets the "f16" field.
func (esbiu *EmStockBasicInfoUpdate) SetF16(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF16(s)
	return esbiu
}

// SetNillableF16 sets the "f16" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF16(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF16(*s)
	}
	return esbiu
}

// ClearF16 clears the value of the "f16" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF16() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF16()
	return esbiu
}

// SetF17 sets the "f17" field.
func (esbiu *EmStockBasicInfoUpdate) SetF17(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF17(s)
	return esbiu
}

// SetNillableF17 sets the "f17" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF17(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF17(*s)
	}
	return esbiu
}

// ClearF17 clears the value of the "f17" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF17() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF17()
	return esbiu
}

// SetF18 sets the "f18" field.
func (esbiu *EmStockBasicInfoUpdate) SetF18(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF18(s)
	return esbiu
}

// SetNillableF18 sets the "f18" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF18(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF18(*s)
	}
	return esbiu
}

// ClearF18 clears the value of the "f18" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF18() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF18()
	return esbiu
}

// SetF19 sets the "f19" field.
func (esbiu *EmStockBasicInfoUpdate) SetF19(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF19(s)
	return esbiu
}

// SetNillableF19 sets the "f19" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF19(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF19(*s)
	}
	return esbiu
}

// ClearF19 clears the value of the "f19" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF19() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF19()
	return esbiu
}

// SetF20 sets the "f20" field.
func (esbiu *EmStockBasicInfoUpdate) SetF20(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF20(s)
	return esbiu
}

// SetNillableF20 sets the "f20" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF20(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF20(*s)
	}
	return esbiu
}

// ClearF20 clears the value of the "f20" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF20() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF20()
	return esbiu
}

// SetF21 sets the "f21" field.
func (esbiu *EmStockBasicInfoUpdate) SetF21(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF21(s)
	return esbiu
}

// SetNillableF21 sets the "f21" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF21(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF21(*s)
	}
	return esbiu
}

// ClearF21 clears the value of the "f21" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF21() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF21()
	return esbiu
}

// SetF22 sets the "f22" field.
func (esbiu *EmStockBasicInfoUpdate) SetF22(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF22(s)
	return esbiu
}

// SetNillableF22 sets the "f22" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF22(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF22(*s)
	}
	return esbiu
}

// ClearF22 clears the value of the "f22" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF22() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF22()
	return esbiu
}

// SetF23 sets the "f23" field.
func (esbiu *EmStockBasicInfoUpdate) SetF23(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF23(s)
	return esbiu
}

// SetNillableF23 sets the "f23" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF23(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF23(*s)
	}
	return esbiu
}

// ClearF23 clears the value of the "f23" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF23() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF23()
	return esbiu
}

// SetF24 sets the "f24" field.
func (esbiu *EmStockBasicInfoUpdate) SetF24(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF24(s)
	return esbiu
}

// SetNillableF24 sets the "f24" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF24(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF24(*s)
	}
	return esbiu
}

// ClearF24 clears the value of the "f24" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF24() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF24()
	return esbiu
}

// SetF25 sets the "f25" field.
func (esbiu *EmStockBasicInfoUpdate) SetF25(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF25(s)
	return esbiu
}

// SetNillableF25 sets the "f25" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF25(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF25(*s)
	}
	return esbiu
}

// ClearF25 clears the value of the "f25" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF25() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF25()
	return esbiu
}

// SetF26 sets the "f26" field.
func (esbiu *EmStockBasicInfoUpdate) SetF26(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF26(s)
	return esbiu
}

// SetNillableF26 sets the "f26" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF26(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF26(*s)
	}
	return esbiu
}

// ClearF26 clears the value of the "f26" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF26() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF26()
	return esbiu
}

// SetF27 sets the "f27" field.
func (esbiu *EmStockBasicInfoUpdate) SetF27(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF27(s)
	return esbiu
}

// SetNillableF27 sets the "f27" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF27(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF27(*s)
	}
	return esbiu
}

// ClearF27 clears the value of the "f27" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF27() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF27()
	return esbiu
}

// SetF28 sets the "f28" field.
func (esbiu *EmStockBasicInfoUpdate) SetF28(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF28(s)
	return esbiu
}

// SetNillableF28 sets the "f28" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF28(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF28(*s)
	}
	return esbiu
}

// ClearF28 clears the value of the "f28" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF28() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF28()
	return esbiu
}

// SetF29 sets the "f29" field.
func (esbiu *EmStockBasicInfoUpdate) SetF29(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF29(s)
	return esbiu
}

// SetNillableF29 sets the "f29" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF29(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF29(*s)
	}
	return esbiu
}

// ClearF29 clears the value of the "f29" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF29() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF29()
	return esbiu
}

// SetF30 sets the "f30" field.
func (esbiu *EmStockBasicInfoUpdate) SetF30(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetF30(s)
	return esbiu
}

// SetNillableF30 sets the "f30" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableF30(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetF30(*s)
	}
	return esbiu
}

// ClearF30 clears the value of the "f30" field.
func (esbiu *EmStockBasicInfoUpdate) ClearF30() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearF30()
	return esbiu
}

// SetCreateTime sets the "create_time" field.
func (esbiu *EmStockBasicInfoUpdate) SetCreateTime(t time.Time) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetCreateTime(t)
	return esbiu
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableCreateTime(t *time.Time) *EmStockBasicInfoUpdate {
	if t != nil {
		esbiu.SetCreateTime(*t)
	}
	return esbiu
}

// ClearCreateTime clears the value of the "create_time" field.
func (esbiu *EmStockBasicInfoUpdate) ClearCreateTime() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearCreateTime()
	return esbiu
}

// SetRemarks sets the "remarks" field.
func (esbiu *EmStockBasicInfoUpdate) SetRemarks(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetRemarks(s)
	return esbiu
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableRemarks(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetRemarks(*s)
	}
	return esbiu
}

// ClearRemarks clears the value of the "remarks" field.
func (esbiu *EmStockBasicInfoUpdate) ClearRemarks() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearRemarks()
	return esbiu
}

// SetStatus sets the "status" field.
func (esbiu *EmStockBasicInfoUpdate) SetStatus(s string) *EmStockBasicInfoUpdate {
	esbiu.mutation.SetStatus(s)
	return esbiu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableStatus(s *string) *EmStockBasicInfoUpdate {
	if s != nil {
		esbiu.SetStatus(*s)
	}
	return esbiu
}

// ClearStatus clears the value of the "status" field.
func (esbiu *EmStockBasicInfoUpdate) ClearStatus() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearStatus()
	return esbiu
}

// SetSt1 sets the "st1" field.
func (esbiu *EmStockBasicInfoUpdate) SetSt1(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.ResetSt1()
	esbiu.mutation.SetSt1(i)
	return esbiu
}

// SetNillableSt1 sets the "st1" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableSt1(i *int32) *EmStockBasicInfoUpdate {
	if i != nil {
		esbiu.SetSt1(*i)
	}
	return esbiu
}

// AddSt1 adds i to the "st1" field.
func (esbiu *EmStockBasicInfoUpdate) AddSt1(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.AddSt1(i)
	return esbiu
}

// ClearSt1 clears the value of the "st1" field.
func (esbiu *EmStockBasicInfoUpdate) ClearSt1() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearSt1()
	return esbiu
}

// SetSt2 sets the "st2" field.
func (esbiu *EmStockBasicInfoUpdate) SetSt2(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.ResetSt2()
	esbiu.mutation.SetSt2(i)
	return esbiu
}

// SetNillableSt2 sets the "st2" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableSt2(i *int32) *EmStockBasicInfoUpdate {
	if i != nil {
		esbiu.SetSt2(*i)
	}
	return esbiu
}

// AddSt2 adds i to the "st2" field.
func (esbiu *EmStockBasicInfoUpdate) AddSt2(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.AddSt2(i)
	return esbiu
}

// ClearSt2 clears the value of the "st2" field.
func (esbiu *EmStockBasicInfoUpdate) ClearSt2() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearSt2()
	return esbiu
}

// SetSt3 sets the "st3" field.
func (esbiu *EmStockBasicInfoUpdate) SetSt3(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.ResetSt3()
	esbiu.mutation.SetSt3(i)
	return esbiu
}

// SetNillableSt3 sets the "st3" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableSt3(i *int32) *EmStockBasicInfoUpdate {
	if i != nil {
		esbiu.SetSt3(*i)
	}
	return esbiu
}

// AddSt3 adds i to the "st3" field.
func (esbiu *EmStockBasicInfoUpdate) AddSt3(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.AddSt3(i)
	return esbiu
}

// ClearSt3 clears the value of the "st3" field.
func (esbiu *EmStockBasicInfoUpdate) ClearSt3() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearSt3()
	return esbiu
}

// SetSt4 sets the "st4" field.
func (esbiu *EmStockBasicInfoUpdate) SetSt4(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.ResetSt4()
	esbiu.mutation.SetSt4(i)
	return esbiu
}

// SetNillableSt4 sets the "st4" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableSt4(i *int32) *EmStockBasicInfoUpdate {
	if i != nil {
		esbiu.SetSt4(*i)
	}
	return esbiu
}

// AddSt4 adds i to the "st4" field.
func (esbiu *EmStockBasicInfoUpdate) AddSt4(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.AddSt4(i)
	return esbiu
}

// ClearSt4 clears the value of the "st4" field.
func (esbiu *EmStockBasicInfoUpdate) ClearSt4() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearSt4()
	return esbiu
}

// SetSt5 sets the "st5" field.
func (esbiu *EmStockBasicInfoUpdate) SetSt5(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.ResetSt5()
	esbiu.mutation.SetSt5(i)
	return esbiu
}

// SetNillableSt5 sets the "st5" field if the given value is not nil.
func (esbiu *EmStockBasicInfoUpdate) SetNillableSt5(i *int32) *EmStockBasicInfoUpdate {
	if i != nil {
		esbiu.SetSt5(*i)
	}
	return esbiu
}

// AddSt5 adds i to the "st5" field.
func (esbiu *EmStockBasicInfoUpdate) AddSt5(i int32) *EmStockBasicInfoUpdate {
	esbiu.mutation.AddSt5(i)
	return esbiu
}

// ClearSt5 clears the value of the "st5" field.
func (esbiu *EmStockBasicInfoUpdate) ClearSt5() *EmStockBasicInfoUpdate {
	esbiu.mutation.ClearSt5()
	return esbiu
}

// Mutation returns the EmStockBasicInfoMutation object of the builder.
func (esbiu *EmStockBasicInfoUpdate) Mutation() *EmStockBasicInfoMutation {
	return esbiu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (esbiu *EmStockBasicInfoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, esbiu.sqlSave, esbiu.mutation, esbiu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (esbiu *EmStockBasicInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := esbiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (esbiu *EmStockBasicInfoUpdate) Exec(ctx context.Context) error {
	_, err := esbiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (esbiu *EmStockBasicInfoUpdate) ExecX(ctx context.Context) {
	if err := esbiu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (esbiu *EmStockBasicInfoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(emstockbasicinfo.Table, emstockbasicinfo.Columns, sqlgraph.NewFieldSpec(emstockbasicinfo.FieldID, field.TypeInt32))
	if ps := esbiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := esbiu.mutation.F1(); ok {
		_spec.SetField(emstockbasicinfo.FieldF1, field.TypeString, value)
	}
	if esbiu.mutation.F1Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF1, field.TypeString)
	}
	if value, ok := esbiu.mutation.F2(); ok {
		_spec.SetField(emstockbasicinfo.FieldF2, field.TypeString, value)
	}
	if esbiu.mutation.F2Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF2, field.TypeString)
	}
	if value, ok := esbiu.mutation.F3(); ok {
		_spec.SetField(emstockbasicinfo.FieldF3, field.TypeString, value)
	}
	if esbiu.mutation.F3Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF3, field.TypeString)
	}
	if value, ok := esbiu.mutation.F4(); ok {
		_spec.SetField(emstockbasicinfo.FieldF4, field.TypeString, value)
	}
	if esbiu.mutation.F4Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF4, field.TypeString)
	}
	if value, ok := esbiu.mutation.F5(); ok {
		_spec.SetField(emstockbasicinfo.FieldF5, field.TypeString, value)
	}
	if esbiu.mutation.F5Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF5, field.TypeString)
	}
	if value, ok := esbiu.mutation.F6(); ok {
		_spec.SetField(emstockbasicinfo.FieldF6, field.TypeString, value)
	}
	if esbiu.mutation.F6Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF6, field.TypeString)
	}
	if value, ok := esbiu.mutation.F7(); ok {
		_spec.SetField(emstockbasicinfo.FieldF7, field.TypeString, value)
	}
	if esbiu.mutation.F7Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF7, field.TypeString)
	}
	if value, ok := esbiu.mutation.F8(); ok {
		_spec.SetField(emstockbasicinfo.FieldF8, field.TypeString, value)
	}
	if esbiu.mutation.F8Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF8, field.TypeString)
	}
	if value, ok := esbiu.mutation.F9(); ok {
		_spec.SetField(emstockbasicinfo.FieldF9, field.TypeString, value)
	}
	if esbiu.mutation.F9Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF9, field.TypeString)
	}
	if value, ok := esbiu.mutation.F10(); ok {
		_spec.SetField(emstockbasicinfo.FieldF10, field.TypeString, value)
	}
	if esbiu.mutation.F10Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF10, field.TypeString)
	}
	if value, ok := esbiu.mutation.F11(); ok {
		_spec.SetField(emstockbasicinfo.FieldF11, field.TypeString, value)
	}
	if esbiu.mutation.F11Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF11, field.TypeString)
	}
	if value, ok := esbiu.mutation.F12(); ok {
		_spec.SetField(emstockbasicinfo.FieldF12, field.TypeString, value)
	}
	if esbiu.mutation.F12Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF12, field.TypeString)
	}
	if value, ok := esbiu.mutation.F13(); ok {
		_spec.SetField(emstockbasicinfo.FieldF13, field.TypeString, value)
	}
	if esbiu.mutation.F13Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF13, field.TypeString)
	}
	if value, ok := esbiu.mutation.F14(); ok {
		_spec.SetField(emstockbasicinfo.FieldF14, field.TypeString, value)
	}
	if esbiu.mutation.F14Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF14, field.TypeString)
	}
	if value, ok := esbiu.mutation.F15(); ok {
		_spec.SetField(emstockbasicinfo.FieldF15, field.TypeString, value)
	}
	if esbiu.mutation.F15Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF15, field.TypeString)
	}
	if value, ok := esbiu.mutation.F16(); ok {
		_spec.SetField(emstockbasicinfo.FieldF16, field.TypeString, value)
	}
	if esbiu.mutation.F16Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF16, field.TypeString)
	}
	if value, ok := esbiu.mutation.F17(); ok {
		_spec.SetField(emstockbasicinfo.FieldF17, field.TypeString, value)
	}
	if esbiu.mutation.F17Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF17, field.TypeString)
	}
	if value, ok := esbiu.mutation.F18(); ok {
		_spec.SetField(emstockbasicinfo.FieldF18, field.TypeString, value)
	}
	if esbiu.mutation.F18Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF18, field.TypeString)
	}
	if value, ok := esbiu.mutation.F19(); ok {
		_spec.SetField(emstockbasicinfo.FieldF19, field.TypeString, value)
	}
	if esbiu.mutation.F19Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF19, field.TypeString)
	}
	if value, ok := esbiu.mutation.F20(); ok {
		_spec.SetField(emstockbasicinfo.FieldF20, field.TypeString, value)
	}
	if esbiu.mutation.F20Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF20, field.TypeString)
	}
	if value, ok := esbiu.mutation.F21(); ok {
		_spec.SetField(emstockbasicinfo.FieldF21, field.TypeString, value)
	}
	if esbiu.mutation.F21Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF21, field.TypeString)
	}
	if value, ok := esbiu.mutation.F22(); ok {
		_spec.SetField(emstockbasicinfo.FieldF22, field.TypeString, value)
	}
	if esbiu.mutation.F22Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF22, field.TypeString)
	}
	if value, ok := esbiu.mutation.F23(); ok {
		_spec.SetField(emstockbasicinfo.FieldF23, field.TypeString, value)
	}
	if esbiu.mutation.F23Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF23, field.TypeString)
	}
	if value, ok := esbiu.mutation.F24(); ok {
		_spec.SetField(emstockbasicinfo.FieldF24, field.TypeString, value)
	}
	if esbiu.mutation.F24Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF24, field.TypeString)
	}
	if value, ok := esbiu.mutation.F25(); ok {
		_spec.SetField(emstockbasicinfo.FieldF25, field.TypeString, value)
	}
	if esbiu.mutation.F25Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF25, field.TypeString)
	}
	if value, ok := esbiu.mutation.F26(); ok {
		_spec.SetField(emstockbasicinfo.FieldF26, field.TypeString, value)
	}
	if esbiu.mutation.F26Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF26, field.TypeString)
	}
	if value, ok := esbiu.mutation.F27(); ok {
		_spec.SetField(emstockbasicinfo.FieldF27, field.TypeString, value)
	}
	if esbiu.mutation.F27Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF27, field.TypeString)
	}
	if value, ok := esbiu.mutation.F28(); ok {
		_spec.SetField(emstockbasicinfo.FieldF28, field.TypeString, value)
	}
	if esbiu.mutation.F28Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF28, field.TypeString)
	}
	if value, ok := esbiu.mutation.F29(); ok {
		_spec.SetField(emstockbasicinfo.FieldF29, field.TypeString, value)
	}
	if esbiu.mutation.F29Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF29, field.TypeString)
	}
	if value, ok := esbiu.mutation.F30(); ok {
		_spec.SetField(emstockbasicinfo.FieldF30, field.TypeString, value)
	}
	if esbiu.mutation.F30Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF30, field.TypeString)
	}
	if value, ok := esbiu.mutation.CreateTime(); ok {
		_spec.SetField(emstockbasicinfo.FieldCreateTime, field.TypeTime, value)
	}
	if esbiu.mutation.CreateTimeCleared() {
		_spec.ClearField(emstockbasicinfo.FieldCreateTime, field.TypeTime)
	}
	if value, ok := esbiu.mutation.Remarks(); ok {
		_spec.SetField(emstockbasicinfo.FieldRemarks, field.TypeString, value)
	}
	if esbiu.mutation.RemarksCleared() {
		_spec.ClearField(emstockbasicinfo.FieldRemarks, field.TypeString)
	}
	if value, ok := esbiu.mutation.Status(); ok {
		_spec.SetField(emstockbasicinfo.FieldStatus, field.TypeString, value)
	}
	if esbiu.mutation.StatusCleared() {
		_spec.ClearField(emstockbasicinfo.FieldStatus, field.TypeString)
	}
	if value, ok := esbiu.mutation.St1(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt1, field.TypeInt32, value)
	}
	if value, ok := esbiu.mutation.AddedSt1(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt1, field.TypeInt32, value)
	}
	if esbiu.mutation.St1Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt1, field.TypeInt32)
	}
	if value, ok := esbiu.mutation.St2(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt2, field.TypeInt32, value)
	}
	if value, ok := esbiu.mutation.AddedSt2(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt2, field.TypeInt32, value)
	}
	if esbiu.mutation.St2Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt2, field.TypeInt32)
	}
	if value, ok := esbiu.mutation.St3(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt3, field.TypeInt32, value)
	}
	if value, ok := esbiu.mutation.AddedSt3(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt3, field.TypeInt32, value)
	}
	if esbiu.mutation.St3Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt3, field.TypeInt32)
	}
	if value, ok := esbiu.mutation.St4(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt4, field.TypeInt32, value)
	}
	if value, ok := esbiu.mutation.AddedSt4(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt4, field.TypeInt32, value)
	}
	if esbiu.mutation.St4Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt4, field.TypeInt32)
	}
	if value, ok := esbiu.mutation.St5(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt5, field.TypeInt32, value)
	}
	if value, ok := esbiu.mutation.AddedSt5(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt5, field.TypeInt32, value)
	}
	if esbiu.mutation.St5Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt5, field.TypeInt32)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, esbiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emstockbasicinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	esbiu.mutation.done = true
	return n, nil
}

// EmStockBasicInfoUpdateOne is the builder for updating a single EmStockBasicInfo entity.
type EmStockBasicInfoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmStockBasicInfoMutation
}

// SetF1 sets the "f1" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF1(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF1(s)
	return esbiuo
}

// SetNillableF1 sets the "f1" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF1(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF1(*s)
	}
	return esbiuo
}

// ClearF1 clears the value of the "f1" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF1() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF1()
	return esbiuo
}

// SetF2 sets the "f2" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF2(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF2(s)
	return esbiuo
}

// SetNillableF2 sets the "f2" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF2(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF2(*s)
	}
	return esbiuo
}

// ClearF2 clears the value of the "f2" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF2() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF2()
	return esbiuo
}

// SetF3 sets the "f3" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF3(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF3(s)
	return esbiuo
}

// SetNillableF3 sets the "f3" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF3(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF3(*s)
	}
	return esbiuo
}

// ClearF3 clears the value of the "f3" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF3() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF3()
	return esbiuo
}

// SetF4 sets the "f4" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF4(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF4(s)
	return esbiuo
}

// SetNillableF4 sets the "f4" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF4(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF4(*s)
	}
	return esbiuo
}

// ClearF4 clears the value of the "f4" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF4() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF4()
	return esbiuo
}

// SetF5 sets the "f5" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF5(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF5(s)
	return esbiuo
}

// SetNillableF5 sets the "f5" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF5(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF5(*s)
	}
	return esbiuo
}

// ClearF5 clears the value of the "f5" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF5() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF5()
	return esbiuo
}

// SetF6 sets the "f6" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF6(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF6(s)
	return esbiuo
}

// SetNillableF6 sets the "f6" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF6(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF6(*s)
	}
	return esbiuo
}

// ClearF6 clears the value of the "f6" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF6() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF6()
	return esbiuo
}

// SetF7 sets the "f7" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF7(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF7(s)
	return esbiuo
}

// SetNillableF7 sets the "f7" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF7(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF7(*s)
	}
	return esbiuo
}

// ClearF7 clears the value of the "f7" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF7() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF7()
	return esbiuo
}

// SetF8 sets the "f8" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF8(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF8(s)
	return esbiuo
}

// SetNillableF8 sets the "f8" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF8(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF8(*s)
	}
	return esbiuo
}

// ClearF8 clears the value of the "f8" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF8() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF8()
	return esbiuo
}

// SetF9 sets the "f9" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF9(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF9(s)
	return esbiuo
}

// SetNillableF9 sets the "f9" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF9(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF9(*s)
	}
	return esbiuo
}

// ClearF9 clears the value of the "f9" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF9() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF9()
	return esbiuo
}

// SetF10 sets the "f10" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF10(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF10(s)
	return esbiuo
}

// SetNillableF10 sets the "f10" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF10(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF10(*s)
	}
	return esbiuo
}

// ClearF10 clears the value of the "f10" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF10() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF10()
	return esbiuo
}

// SetF11 sets the "f11" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF11(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF11(s)
	return esbiuo
}

// SetNillableF11 sets the "f11" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF11(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF11(*s)
	}
	return esbiuo
}

// ClearF11 clears the value of the "f11" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF11() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF11()
	return esbiuo
}

// SetF12 sets the "f12" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF12(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF12(s)
	return esbiuo
}

// SetNillableF12 sets the "f12" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF12(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF12(*s)
	}
	return esbiuo
}

// ClearF12 clears the value of the "f12" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF12() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF12()
	return esbiuo
}

// SetF13 sets the "f13" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF13(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF13(s)
	return esbiuo
}

// SetNillableF13 sets the "f13" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF13(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF13(*s)
	}
	return esbiuo
}

// ClearF13 clears the value of the "f13" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF13() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF13()
	return esbiuo
}

// SetF14 sets the "f14" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF14(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF14(s)
	return esbiuo
}

// SetNillableF14 sets the "f14" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF14(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF14(*s)
	}
	return esbiuo
}

// ClearF14 clears the value of the "f14" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF14() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF14()
	return esbiuo
}

// SetF15 sets the "f15" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF15(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF15(s)
	return esbiuo
}

// SetNillableF15 sets the "f15" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF15(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF15(*s)
	}
	return esbiuo
}

// ClearF15 clears the value of the "f15" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF15() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF15()
	return esbiuo
}

// SetF16 sets the "f16" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF16(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF16(s)
	return esbiuo
}

// SetNillableF16 sets the "f16" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF16(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF16(*s)
	}
	return esbiuo
}

// ClearF16 clears the value of the "f16" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF16() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF16()
	return esbiuo
}

// SetF17 sets the "f17" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF17(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF17(s)
	return esbiuo
}

// SetNillableF17 sets the "f17" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF17(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF17(*s)
	}
	return esbiuo
}

// ClearF17 clears the value of the "f17" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF17() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF17()
	return esbiuo
}

// SetF18 sets the "f18" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF18(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF18(s)
	return esbiuo
}

// SetNillableF18 sets the "f18" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF18(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF18(*s)
	}
	return esbiuo
}

// ClearF18 clears the value of the "f18" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF18() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF18()
	return esbiuo
}

// SetF19 sets the "f19" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF19(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF19(s)
	return esbiuo
}

// SetNillableF19 sets the "f19" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF19(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF19(*s)
	}
	return esbiuo
}

// ClearF19 clears the value of the "f19" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF19() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF19()
	return esbiuo
}

// SetF20 sets the "f20" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF20(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF20(s)
	return esbiuo
}

// SetNillableF20 sets the "f20" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF20(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF20(*s)
	}
	return esbiuo
}

// ClearF20 clears the value of the "f20" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF20() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF20()
	return esbiuo
}

// SetF21 sets the "f21" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF21(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF21(s)
	return esbiuo
}

// SetNillableF21 sets the "f21" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF21(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF21(*s)
	}
	return esbiuo
}

// ClearF21 clears the value of the "f21" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF21() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF21()
	return esbiuo
}

// SetF22 sets the "f22" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF22(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF22(s)
	return esbiuo
}

// SetNillableF22 sets the "f22" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF22(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF22(*s)
	}
	return esbiuo
}

// ClearF22 clears the value of the "f22" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF22() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF22()
	return esbiuo
}

// SetF23 sets the "f23" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF23(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF23(s)
	return esbiuo
}

// SetNillableF23 sets the "f23" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF23(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF23(*s)
	}
	return esbiuo
}

// ClearF23 clears the value of the "f23" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF23() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF23()
	return esbiuo
}

// SetF24 sets the "f24" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF24(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF24(s)
	return esbiuo
}

// SetNillableF24 sets the "f24" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF24(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF24(*s)
	}
	return esbiuo
}

// ClearF24 clears the value of the "f24" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF24() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF24()
	return esbiuo
}

// SetF25 sets the "f25" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF25(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF25(s)
	return esbiuo
}

// SetNillableF25 sets the "f25" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF25(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF25(*s)
	}
	return esbiuo
}

// ClearF25 clears the value of the "f25" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF25() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF25()
	return esbiuo
}

// SetF26 sets the "f26" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF26(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF26(s)
	return esbiuo
}

// SetNillableF26 sets the "f26" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF26(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF26(*s)
	}
	return esbiuo
}

// ClearF26 clears the value of the "f26" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF26() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF26()
	return esbiuo
}

// SetF27 sets the "f27" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF27(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF27(s)
	return esbiuo
}

// SetNillableF27 sets the "f27" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF27(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF27(*s)
	}
	return esbiuo
}

// ClearF27 clears the value of the "f27" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF27() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF27()
	return esbiuo
}

// SetF28 sets the "f28" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF28(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF28(s)
	return esbiuo
}

// SetNillableF28 sets the "f28" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF28(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF28(*s)
	}
	return esbiuo
}

// ClearF28 clears the value of the "f28" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF28() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF28()
	return esbiuo
}

// SetF29 sets the "f29" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF29(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF29(s)
	return esbiuo
}

// SetNillableF29 sets the "f29" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF29(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF29(*s)
	}
	return esbiuo
}

// ClearF29 clears the value of the "f29" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF29() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF29()
	return esbiuo
}

// SetF30 sets the "f30" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetF30(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetF30(s)
	return esbiuo
}

// SetNillableF30 sets the "f30" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableF30(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetF30(*s)
	}
	return esbiuo
}

// ClearF30 clears the value of the "f30" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearF30() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearF30()
	return esbiuo
}

// SetCreateTime sets the "create_time" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetCreateTime(t time.Time) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetCreateTime(t)
	return esbiuo
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableCreateTime(t *time.Time) *EmStockBasicInfoUpdateOne {
	if t != nil {
		esbiuo.SetCreateTime(*t)
	}
	return esbiuo
}

// ClearCreateTime clears the value of the "create_time" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearCreateTime() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearCreateTime()
	return esbiuo
}

// SetRemarks sets the "remarks" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetRemarks(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetRemarks(s)
	return esbiuo
}

// SetNillableRemarks sets the "remarks" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableRemarks(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetRemarks(*s)
	}
	return esbiuo
}

// ClearRemarks clears the value of the "remarks" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearRemarks() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearRemarks()
	return esbiuo
}

// SetStatus sets the "status" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetStatus(s string) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.SetStatus(s)
	return esbiuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableStatus(s *string) *EmStockBasicInfoUpdateOne {
	if s != nil {
		esbiuo.SetStatus(*s)
	}
	return esbiuo
}

// ClearStatus clears the value of the "status" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearStatus() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearStatus()
	return esbiuo
}

// SetSt1 sets the "st1" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetSt1(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ResetSt1()
	esbiuo.mutation.SetSt1(i)
	return esbiuo
}

// SetNillableSt1 sets the "st1" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableSt1(i *int32) *EmStockBasicInfoUpdateOne {
	if i != nil {
		esbiuo.SetSt1(*i)
	}
	return esbiuo
}

// AddSt1 adds i to the "st1" field.
func (esbiuo *EmStockBasicInfoUpdateOne) AddSt1(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.AddSt1(i)
	return esbiuo
}

// ClearSt1 clears the value of the "st1" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearSt1() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearSt1()
	return esbiuo
}

// SetSt2 sets the "st2" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetSt2(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ResetSt2()
	esbiuo.mutation.SetSt2(i)
	return esbiuo
}

// SetNillableSt2 sets the "st2" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableSt2(i *int32) *EmStockBasicInfoUpdateOne {
	if i != nil {
		esbiuo.SetSt2(*i)
	}
	return esbiuo
}

// AddSt2 adds i to the "st2" field.
func (esbiuo *EmStockBasicInfoUpdateOne) AddSt2(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.AddSt2(i)
	return esbiuo
}

// ClearSt2 clears the value of the "st2" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearSt2() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearSt2()
	return esbiuo
}

// SetSt3 sets the "st3" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetSt3(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ResetSt3()
	esbiuo.mutation.SetSt3(i)
	return esbiuo
}

// SetNillableSt3 sets the "st3" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableSt3(i *int32) *EmStockBasicInfoUpdateOne {
	if i != nil {
		esbiuo.SetSt3(*i)
	}
	return esbiuo
}

// AddSt3 adds i to the "st3" field.
func (esbiuo *EmStockBasicInfoUpdateOne) AddSt3(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.AddSt3(i)
	return esbiuo
}

// ClearSt3 clears the value of the "st3" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearSt3() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearSt3()
	return esbiuo
}

// SetSt4 sets the "st4" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetSt4(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ResetSt4()
	esbiuo.mutation.SetSt4(i)
	return esbiuo
}

// SetNillableSt4 sets the "st4" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableSt4(i *int32) *EmStockBasicInfoUpdateOne {
	if i != nil {
		esbiuo.SetSt4(*i)
	}
	return esbiuo
}

// AddSt4 adds i to the "st4" field.
func (esbiuo *EmStockBasicInfoUpdateOne) AddSt4(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.AddSt4(i)
	return esbiuo
}

// ClearSt4 clears the value of the "st4" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearSt4() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearSt4()
	return esbiuo
}

// SetSt5 sets the "st5" field.
func (esbiuo *EmStockBasicInfoUpdateOne) SetSt5(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ResetSt5()
	esbiuo.mutation.SetSt5(i)
	return esbiuo
}

// SetNillableSt5 sets the "st5" field if the given value is not nil.
func (esbiuo *EmStockBasicInfoUpdateOne) SetNillableSt5(i *int32) *EmStockBasicInfoUpdateOne {
	if i != nil {
		esbiuo.SetSt5(*i)
	}
	return esbiuo
}

// AddSt5 adds i to the "st5" field.
func (esbiuo *EmStockBasicInfoUpdateOne) AddSt5(i int32) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.AddSt5(i)
	return esbiuo
}

// ClearSt5 clears the value of the "st5" field.
func (esbiuo *EmStockBasicInfoUpdateOne) ClearSt5() *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.ClearSt5()
	return esbiuo
}

// Mutation returns the EmStockBasicInfoMutation object of the builder.
func (esbiuo *EmStockBasicInfoUpdateOne) Mutation() *EmStockBasicInfoMutation {
	return esbiuo.mutation
}

// Where appends a list predicates to the EmStockBasicInfoUpdate builder.
func (esbiuo *EmStockBasicInfoUpdateOne) Where(ps ...predicate.EmStockBasicInfo) *EmStockBasicInfoUpdateOne {
	esbiuo.mutation.Where(ps...)
	return esbiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (esbiuo *EmStockBasicInfoUpdateOne) Select(field string, fields ...string) *EmStockBasicInfoUpdateOne {
	esbiuo.fields = append([]string{field}, fields...)
	return esbiuo
}

// Save executes the query and returns the updated EmStockBasicInfo entity.
func (esbiuo *EmStockBasicInfoUpdateOne) Save(ctx context.Context) (*EmStockBasicInfo, error) {
	return withHooks(ctx, esbiuo.sqlSave, esbiuo.mutation, esbiuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (esbiuo *EmStockBasicInfoUpdateOne) SaveX(ctx context.Context) *EmStockBasicInfo {
	node, err := esbiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (esbiuo *EmStockBasicInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := esbiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (esbiuo *EmStockBasicInfoUpdateOne) ExecX(ctx context.Context) {
	if err := esbiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (esbiuo *EmStockBasicInfoUpdateOne) sqlSave(ctx context.Context) (_node *EmStockBasicInfo, err error) {
	_spec := sqlgraph.NewUpdateSpec(emstockbasicinfo.Table, emstockbasicinfo.Columns, sqlgraph.NewFieldSpec(emstockbasicinfo.FieldID, field.TypeInt32))
	id, ok := esbiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmStockBasicInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := esbiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emstockbasicinfo.FieldID)
		for _, f := range fields {
			if !emstockbasicinfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emstockbasicinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := esbiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := esbiuo.mutation.F1(); ok {
		_spec.SetField(emstockbasicinfo.FieldF1, field.TypeString, value)
	}
	if esbiuo.mutation.F1Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF1, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F2(); ok {
		_spec.SetField(emstockbasicinfo.FieldF2, field.TypeString, value)
	}
	if esbiuo.mutation.F2Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF2, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F3(); ok {
		_spec.SetField(emstockbasicinfo.FieldF3, field.TypeString, value)
	}
	if esbiuo.mutation.F3Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF3, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F4(); ok {
		_spec.SetField(emstockbasicinfo.FieldF4, field.TypeString, value)
	}
	if esbiuo.mutation.F4Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF4, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F5(); ok {
		_spec.SetField(emstockbasicinfo.FieldF5, field.TypeString, value)
	}
	if esbiuo.mutation.F5Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF5, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F6(); ok {
		_spec.SetField(emstockbasicinfo.FieldF6, field.TypeString, value)
	}
	if esbiuo.mutation.F6Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF6, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F7(); ok {
		_spec.SetField(emstockbasicinfo.FieldF7, field.TypeString, value)
	}
	if esbiuo.mutation.F7Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF7, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F8(); ok {
		_spec.SetField(emstockbasicinfo.FieldF8, field.TypeString, value)
	}
	if esbiuo.mutation.F8Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF8, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F9(); ok {
		_spec.SetField(emstockbasicinfo.FieldF9, field.TypeString, value)
	}
	if esbiuo.mutation.F9Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF9, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F10(); ok {
		_spec.SetField(emstockbasicinfo.FieldF10, field.TypeString, value)
	}
	if esbiuo.mutation.F10Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF10, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F11(); ok {
		_spec.SetField(emstockbasicinfo.FieldF11, field.TypeString, value)
	}
	if esbiuo.mutation.F11Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF11, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F12(); ok {
		_spec.SetField(emstockbasicinfo.FieldF12, field.TypeString, value)
	}
	if esbiuo.mutation.F12Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF12, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F13(); ok {
		_spec.SetField(emstockbasicinfo.FieldF13, field.TypeString, value)
	}
	if esbiuo.mutation.F13Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF13, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F14(); ok {
		_spec.SetField(emstockbasicinfo.FieldF14, field.TypeString, value)
	}
	if esbiuo.mutation.F14Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF14, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F15(); ok {
		_spec.SetField(emstockbasicinfo.FieldF15, field.TypeString, value)
	}
	if esbiuo.mutation.F15Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF15, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F16(); ok {
		_spec.SetField(emstockbasicinfo.FieldF16, field.TypeString, value)
	}
	if esbiuo.mutation.F16Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF16, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F17(); ok {
		_spec.SetField(emstockbasicinfo.FieldF17, field.TypeString, value)
	}
	if esbiuo.mutation.F17Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF17, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F18(); ok {
		_spec.SetField(emstockbasicinfo.FieldF18, field.TypeString, value)
	}
	if esbiuo.mutation.F18Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF18, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F19(); ok {
		_spec.SetField(emstockbasicinfo.FieldF19, field.TypeString, value)
	}
	if esbiuo.mutation.F19Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF19, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F20(); ok {
		_spec.SetField(emstockbasicinfo.FieldF20, field.TypeString, value)
	}
	if esbiuo.mutation.F20Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF20, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F21(); ok {
		_spec.SetField(emstockbasicinfo.FieldF21, field.TypeString, value)
	}
	if esbiuo.mutation.F21Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF21, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F22(); ok {
		_spec.SetField(emstockbasicinfo.FieldF22, field.TypeString, value)
	}
	if esbiuo.mutation.F22Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF22, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F23(); ok {
		_spec.SetField(emstockbasicinfo.FieldF23, field.TypeString, value)
	}
	if esbiuo.mutation.F23Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF23, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F24(); ok {
		_spec.SetField(emstockbasicinfo.FieldF24, field.TypeString, value)
	}
	if esbiuo.mutation.F24Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF24, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F25(); ok {
		_spec.SetField(emstockbasicinfo.FieldF25, field.TypeString, value)
	}
	if esbiuo.mutation.F25Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF25, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F26(); ok {
		_spec.SetField(emstockbasicinfo.FieldF26, field.TypeString, value)
	}
	if esbiuo.mutation.F26Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF26, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F27(); ok {
		_spec.SetField(emstockbasicinfo.FieldF27, field.TypeString, value)
	}
	if esbiuo.mutation.F27Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF27, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F28(); ok {
		_spec.SetField(emstockbasicinfo.FieldF28, field.TypeString, value)
	}
	if esbiuo.mutation.F28Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF28, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F29(); ok {
		_spec.SetField(emstockbasicinfo.FieldF29, field.TypeString, value)
	}
	if esbiuo.mutation.F29Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF29, field.TypeString)
	}
	if value, ok := esbiuo.mutation.F30(); ok {
		_spec.SetField(emstockbasicinfo.FieldF30, field.TypeString, value)
	}
	if esbiuo.mutation.F30Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldF30, field.TypeString)
	}
	if value, ok := esbiuo.mutation.CreateTime(); ok {
		_spec.SetField(emstockbasicinfo.FieldCreateTime, field.TypeTime, value)
	}
	if esbiuo.mutation.CreateTimeCleared() {
		_spec.ClearField(emstockbasicinfo.FieldCreateTime, field.TypeTime)
	}
	if value, ok := esbiuo.mutation.Remarks(); ok {
		_spec.SetField(emstockbasicinfo.FieldRemarks, field.TypeString, value)
	}
	if esbiuo.mutation.RemarksCleared() {
		_spec.ClearField(emstockbasicinfo.FieldRemarks, field.TypeString)
	}
	if value, ok := esbiuo.mutation.Status(); ok {
		_spec.SetField(emstockbasicinfo.FieldStatus, field.TypeString, value)
	}
	if esbiuo.mutation.StatusCleared() {
		_spec.ClearField(emstockbasicinfo.FieldStatus, field.TypeString)
	}
	if value, ok := esbiuo.mutation.St1(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt1, field.TypeInt32, value)
	}
	if value, ok := esbiuo.mutation.AddedSt1(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt1, field.TypeInt32, value)
	}
	if esbiuo.mutation.St1Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt1, field.TypeInt32)
	}
	if value, ok := esbiuo.mutation.St2(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt2, field.TypeInt32, value)
	}
	if value, ok := esbiuo.mutation.AddedSt2(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt2, field.TypeInt32, value)
	}
	if esbiuo.mutation.St2Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt2, field.TypeInt32)
	}
	if value, ok := esbiuo.mutation.St3(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt3, field.TypeInt32, value)
	}
	if value, ok := esbiuo.mutation.AddedSt3(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt3, field.TypeInt32, value)
	}
	if esbiuo.mutation.St3Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt3, field.TypeInt32)
	}
	if value, ok := esbiuo.mutation.St4(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt4, field.TypeInt32, value)
	}
	if value, ok := esbiuo.mutation.AddedSt4(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt4, field.TypeInt32, value)
	}
	if esbiuo.mutation.St4Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt4, field.TypeInt32)
	}
	if value, ok := esbiuo.mutation.St5(); ok {
		_spec.SetField(emstockbasicinfo.FieldSt5, field.TypeInt32, value)
	}
	if value, ok := esbiuo.mutation.AddedSt5(); ok {
		_spec.AddField(emstockbasicinfo.FieldSt5, field.TypeInt32, value)
	}
	if esbiuo.mutation.St5Cleared() {
		_spec.ClearField(emstockbasicinfo.FieldSt5, field.TypeInt32)
	}
	_node = &EmStockBasicInfo{config: esbiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, esbiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emstockbasicinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	esbiuo.mutation.done = true
	return _node, nil
}
