// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emstockbasicinfo"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/predicate"
)

// EmStockBasicInfoQuery is the builder for querying EmStockBasicInfo entities.
type EmStockBasicInfoQuery struct {
	config
	ctx        *QueryContext
	order      []emstockbasicinfo.OrderOption
	inters     []Interceptor
	predicates []predicate.EmStockBasicInfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EmStockBasicInfoQuery builder.
func (esbiq *EmStockBasicInfoQuery) Where(ps ...predicate.EmStockBasicInfo) *EmStockBasicInfoQuery {
	esbiq.predicates = append(esbiq.predicates, ps...)
	return esbiq
}

// Limit the number of records to be returned by this query.
func (esbiq *EmStockBasicInfoQuery) Limit(limit int) *EmStockBasicInfoQuery {
	esbiq.ctx.Limit = &limit
	return esbiq
}

// Offset to start from.
func (esbiq *EmStockBasicInfoQuery) Offset(offset int) *EmStockBasicInfoQuery {
	esbiq.ctx.Offset = &offset
	return esbiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (esbiq *EmStockBasicInfoQuery) Unique(unique bool) *EmStockBasicInfoQuery {
	esbiq.ctx.Unique = &unique
	return esbiq
}

// Order specifies how the records should be ordered.
func (esbiq *EmStockBasicInfoQuery) Order(o ...emstockbasicinfo.OrderOption) *EmStockBasicInfoQuery {
	esbiq.order = append(esbiq.order, o...)
	return esbiq
}

// First returns the first EmStockBasicInfo entity from the query.
// Returns a *NotFoundError when no EmStockBasicInfo was found.
func (esbiq *EmStockBasicInfoQuery) First(ctx context.Context) (*EmStockBasicInfo, error) {
	nodes, err := esbiq.Limit(1).All(setContextOp(ctx, esbiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{emstockbasicinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (esbiq *EmStockBasicInfoQuery) FirstX(ctx context.Context) *EmStockBasicInfo {
	node, err := esbiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EmStockBasicInfo ID from the query.
// Returns a *NotFoundError when no EmStockBasicInfo ID was found.
func (esbiq *EmStockBasicInfoQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = esbiq.Limit(1).IDs(setContextOp(ctx, esbiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{emstockbasicinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (esbiq *EmStockBasicInfoQuery) FirstIDX(ctx context.Context) int32 {
	id, err := esbiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EmStockBasicInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EmStockBasicInfo entity is found.
// Returns a *NotFoundError when no EmStockBasicInfo entities are found.
func (esbiq *EmStockBasicInfoQuery) Only(ctx context.Context) (*EmStockBasicInfo, error) {
	nodes, err := esbiq.Limit(2).All(setContextOp(ctx, esbiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{emstockbasicinfo.Label}
	default:
		return nil, &NotSingularError{emstockbasicinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (esbiq *EmStockBasicInfoQuery) OnlyX(ctx context.Context) *EmStockBasicInfo {
	node, err := esbiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EmStockBasicInfo ID in the query.
// Returns a *NotSingularError when more than one EmStockBasicInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (esbiq *EmStockBasicInfoQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = esbiq.Limit(2).IDs(setContextOp(ctx, esbiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{emstockbasicinfo.Label}
	default:
		err = &NotSingularError{emstockbasicinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (esbiq *EmStockBasicInfoQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := esbiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EmStockBasicInfos.
func (esbiq *EmStockBasicInfoQuery) All(ctx context.Context) ([]*EmStockBasicInfo, error) {
	ctx = setContextOp(ctx, esbiq.ctx, ent.OpQueryAll)
	if err := esbiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EmStockBasicInfo, *EmStockBasicInfoQuery]()
	return withInterceptors[[]*EmStockBasicInfo](ctx, esbiq, qr, esbiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (esbiq *EmStockBasicInfoQuery) AllX(ctx context.Context) []*EmStockBasicInfo {
	nodes, err := esbiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EmStockBasicInfo IDs.
func (esbiq *EmStockBasicInfoQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if esbiq.ctx.Unique == nil && esbiq.path != nil {
		esbiq.Unique(true)
	}
	ctx = setContextOp(ctx, esbiq.ctx, ent.OpQueryIDs)
	if err = esbiq.Select(emstockbasicinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (esbiq *EmStockBasicInfoQuery) IDsX(ctx context.Context) []int32 {
	ids, err := esbiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (esbiq *EmStockBasicInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, esbiq.ctx, ent.OpQueryCount)
	if err := esbiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, esbiq, querierCount[*EmStockBasicInfoQuery](), esbiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (esbiq *EmStockBasicInfoQuery) CountX(ctx context.Context) int {
	count, err := esbiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (esbiq *EmStockBasicInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, esbiq.ctx, ent.OpQueryExist)
	switch _, err := esbiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (esbiq *EmStockBasicInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := esbiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EmStockBasicInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (esbiq *EmStockBasicInfoQuery) Clone() *EmStockBasicInfoQuery {
	if esbiq == nil {
		return nil
	}
	return &EmStockBasicInfoQuery{
		config:     esbiq.config,
		ctx:        esbiq.ctx.Clone(),
		order:      append([]emstockbasicinfo.OrderOption{}, esbiq.order...),
		inters:     append([]Interceptor{}, esbiq.inters...),
		predicates: append([]predicate.EmStockBasicInfo{}, esbiq.predicates...),
		// clone intermediate query.
		sql:  esbiq.sql.Clone(),
		path: esbiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		F1 string `json:"f1,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EmStockBasicInfo.Query().
//		GroupBy(emstockbasicinfo.FieldF1).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (esbiq *EmStockBasicInfoQuery) GroupBy(field string, fields ...string) *EmStockBasicInfoGroupBy {
	esbiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EmStockBasicInfoGroupBy{build: esbiq}
	grbuild.flds = &esbiq.ctx.Fields
	grbuild.label = emstockbasicinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		F1 string `json:"f1,omitempty"`
//	}
//
//	client.EmStockBasicInfo.Query().
//		Select(emstockbasicinfo.FieldF1).
//		Scan(ctx, &v)
func (esbiq *EmStockBasicInfoQuery) Select(fields ...string) *EmStockBasicInfoSelect {
	esbiq.ctx.Fields = append(esbiq.ctx.Fields, fields...)
	sbuild := &EmStockBasicInfoSelect{EmStockBasicInfoQuery: esbiq}
	sbuild.label = emstockbasicinfo.Label
	sbuild.flds, sbuild.scan = &esbiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EmStockBasicInfoSelect configured with the given aggregations.
func (esbiq *EmStockBasicInfoQuery) Aggregate(fns ...AggregateFunc) *EmStockBasicInfoSelect {
	return esbiq.Select().Aggregate(fns...)
}

func (esbiq *EmStockBasicInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range esbiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, esbiq); err != nil {
				return err
			}
		}
	}
	for _, f := range esbiq.ctx.Fields {
		if !emstockbasicinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if esbiq.path != nil {
		prev, err := esbiq.path(ctx)
		if err != nil {
			return err
		}
		esbiq.sql = prev
	}
	return nil
}

func (esbiq *EmStockBasicInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EmStockBasicInfo, error) {
	var (
		nodes = []*EmStockBasicInfo{}
		_spec = esbiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EmStockBasicInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EmStockBasicInfo{config: esbiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, esbiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (esbiq *EmStockBasicInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := esbiq.querySpec()
	_spec.Node.Columns = esbiq.ctx.Fields
	if len(esbiq.ctx.Fields) > 0 {
		_spec.Unique = esbiq.ctx.Unique != nil && *esbiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, esbiq.driver, _spec)
}

func (esbiq *EmStockBasicInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(emstockbasicinfo.Table, emstockbasicinfo.Columns, sqlgraph.NewFieldSpec(emstockbasicinfo.FieldID, field.TypeInt32))
	_spec.From = esbiq.sql
	if unique := esbiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if esbiq.path != nil {
		_spec.Unique = true
	}
	if fields := esbiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emstockbasicinfo.FieldID)
		for i := range fields {
			if fields[i] != emstockbasicinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := esbiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := esbiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := esbiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := esbiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (esbiq *EmStockBasicInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(esbiq.driver.Dialect())
	t1 := builder.Table(emstockbasicinfo.Table)
	columns := esbiq.ctx.Fields
	if len(columns) == 0 {
		columns = emstockbasicinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if esbiq.sql != nil {
		selector = esbiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if esbiq.ctx.Unique != nil && *esbiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range esbiq.predicates {
		p(selector)
	}
	for _, p := range esbiq.order {
		p(selector)
	}
	if offset := esbiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := esbiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EmStockBasicInfoGroupBy is the group-by builder for EmStockBasicInfo entities.
type EmStockBasicInfoGroupBy struct {
	selector
	build *EmStockBasicInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (esbigb *EmStockBasicInfoGroupBy) Aggregate(fns ...AggregateFunc) *EmStockBasicInfoGroupBy {
	esbigb.fns = append(esbigb.fns, fns...)
	return esbigb
}

// Scan applies the selector query and scans the result into the given value.
func (esbigb *EmStockBasicInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, esbigb.build.ctx, ent.OpQueryGroupBy)
	if err := esbigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmStockBasicInfoQuery, *EmStockBasicInfoGroupBy](ctx, esbigb.build, esbigb, esbigb.build.inters, v)
}

func (esbigb *EmStockBasicInfoGroupBy) sqlScan(ctx context.Context, root *EmStockBasicInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(esbigb.fns))
	for _, fn := range esbigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*esbigb.flds)+len(esbigb.fns))
		for _, f := range *esbigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*esbigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := esbigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EmStockBasicInfoSelect is the builder for selecting fields of EmStockBasicInfo entities.
type EmStockBasicInfoSelect struct {
	*EmStockBasicInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (esbis *EmStockBasicInfoSelect) Aggregate(fns ...AggregateFunc) *EmStockBasicInfoSelect {
	esbis.fns = append(esbis.fns, fns...)
	return esbis
}

// Scan applies the selector query and scans the result into the given value.
func (esbis *EmStockBasicInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, esbis.ctx, ent.OpQuerySelect)
	if err := esbis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmStockBasicInfoQuery, *EmStockBasicInfoSelect](ctx, esbis.EmStockBasicInfoQuery, esbis, esbis.inters, v)
}

func (esbis *EmStockBasicInfoSelect) sqlScan(ctx context.Context, root *EmStockBasicInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(esbis.fns))
	for _, fn := range esbis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*esbis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := esbis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
