// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/emstockwatch"
	"github.com/suyuan32/simple-admin-efinance-rpc/ent/predicate"
)

// EmStockWatchQuery is the builder for querying EmStockWatch entities.
type EmStockWatchQuery struct {
	config
	ctx        *QueryContext
	order      []emstockwatch.OrderOption
	inters     []Interceptor
	predicates []predicate.EmStockWatch
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EmStockWatchQuery builder.
func (eswq *EmStockWatchQuery) Where(ps ...predicate.EmStockWatch) *EmStockWatchQuery {
	eswq.predicates = append(eswq.predicates, ps...)
	return eswq
}

// Limit the number of records to be returned by this query.
func (eswq *EmStockWatchQuery) Limit(limit int) *EmStockWatchQuery {
	eswq.ctx.Limit = &limit
	return eswq
}

// Offset to start from.
func (eswq *EmStockWatchQuery) Offset(offset int) *EmStockWatchQuery {
	eswq.ctx.Offset = &offset
	return eswq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eswq *EmStockWatchQuery) Unique(unique bool) *EmStockWatchQuery {
	eswq.ctx.Unique = &unique
	return eswq
}

// Order specifies how the records should be ordered.
func (eswq *EmStockWatchQuery) Order(o ...emstockwatch.OrderOption) *EmStockWatchQuery {
	eswq.order = append(eswq.order, o...)
	return eswq
}

// First returns the first EmStockWatch entity from the query.
// Returns a *NotFoundError when no EmStockWatch was found.
func (eswq *EmStockWatchQuery) First(ctx context.Context) (*EmStockWatch, error) {
	nodes, err := eswq.Limit(1).All(setContextOp(ctx, eswq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{emstockwatch.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eswq *EmStockWatchQuery) FirstX(ctx context.Context) *EmStockWatch {
	node, err := eswq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EmStockWatch ID from the query.
// Returns a *NotFoundError when no EmStockWatch ID was found.
func (eswq *EmStockWatchQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = eswq.Limit(1).IDs(setContextOp(ctx, eswq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{emstockwatch.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eswq *EmStockWatchQuery) FirstIDX(ctx context.Context) int32 {
	id, err := eswq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EmStockWatch entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EmStockWatch entity is found.
// Returns a *NotFoundError when no EmStockWatch entities are found.
func (eswq *EmStockWatchQuery) Only(ctx context.Context) (*EmStockWatch, error) {
	nodes, err := eswq.Limit(2).All(setContextOp(ctx, eswq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{emstockwatch.Label}
	default:
		return nil, &NotSingularError{emstockwatch.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eswq *EmStockWatchQuery) OnlyX(ctx context.Context) *EmStockWatch {
	node, err := eswq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EmStockWatch ID in the query.
// Returns a *NotSingularError when more than one EmStockWatch ID is found.
// Returns a *NotFoundError when no entities are found.
func (eswq *EmStockWatchQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = eswq.Limit(2).IDs(setContextOp(ctx, eswq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{emstockwatch.Label}
	default:
		err = &NotSingularError{emstockwatch.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eswq *EmStockWatchQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := eswq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EmStockWatches.
func (eswq *EmStockWatchQuery) All(ctx context.Context) ([]*EmStockWatch, error) {
	ctx = setContextOp(ctx, eswq.ctx, ent.OpQueryAll)
	if err := eswq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EmStockWatch, *EmStockWatchQuery]()
	return withInterceptors[[]*EmStockWatch](ctx, eswq, qr, eswq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eswq *EmStockWatchQuery) AllX(ctx context.Context) []*EmStockWatch {
	nodes, err := eswq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EmStockWatch IDs.
func (eswq *EmStockWatchQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if eswq.ctx.Unique == nil && eswq.path != nil {
		eswq.Unique(true)
	}
	ctx = setContextOp(ctx, eswq.ctx, ent.OpQueryIDs)
	if err = eswq.Select(emstockwatch.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eswq *EmStockWatchQuery) IDsX(ctx context.Context) []int32 {
	ids, err := eswq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eswq *EmStockWatchQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eswq.ctx, ent.OpQueryCount)
	if err := eswq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eswq, querierCount[*EmStockWatchQuery](), eswq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eswq *EmStockWatchQuery) CountX(ctx context.Context) int {
	count, err := eswq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eswq *EmStockWatchQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eswq.ctx, ent.OpQueryExist)
	switch _, err := eswq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eswq *EmStockWatchQuery) ExistX(ctx context.Context) bool {
	exist, err := eswq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EmStockWatchQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eswq *EmStockWatchQuery) Clone() *EmStockWatchQuery {
	if eswq == nil {
		return nil
	}
	return &EmStockWatchQuery{
		config:     eswq.config,
		ctx:        eswq.ctx.Clone(),
		order:      append([]emstockwatch.OrderOption{}, eswq.order...),
		inters:     append([]Interceptor{}, eswq.inters...),
		predicates: append([]predicate.EmStockWatch{}, eswq.predicates...),
		// clone intermediate query.
		sql:  eswq.sql.Clone(),
		path: eswq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StockWatchCode string `json:"stock_watch_code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EmStockWatch.Query().
//		GroupBy(emstockwatch.FieldStockWatchCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eswq *EmStockWatchQuery) GroupBy(field string, fields ...string) *EmStockWatchGroupBy {
	eswq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EmStockWatchGroupBy{build: eswq}
	grbuild.flds = &eswq.ctx.Fields
	grbuild.label = emstockwatch.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StockWatchCode string `json:"stock_watch_code,omitempty"`
//	}
//
//	client.EmStockWatch.Query().
//		Select(emstockwatch.FieldStockWatchCode).
//		Scan(ctx, &v)
func (eswq *EmStockWatchQuery) Select(fields ...string) *EmStockWatchSelect {
	eswq.ctx.Fields = append(eswq.ctx.Fields, fields...)
	sbuild := &EmStockWatchSelect{EmStockWatchQuery: eswq}
	sbuild.label = emstockwatch.Label
	sbuild.flds, sbuild.scan = &eswq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EmStockWatchSelect configured with the given aggregations.
func (eswq *EmStockWatchQuery) Aggregate(fns ...AggregateFunc) *EmStockWatchSelect {
	return eswq.Select().Aggregate(fns...)
}

func (eswq *EmStockWatchQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eswq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eswq); err != nil {
				return err
			}
		}
	}
	for _, f := range eswq.ctx.Fields {
		if !emstockwatch.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eswq.path != nil {
		prev, err := eswq.path(ctx)
		if err != nil {
			return err
		}
		eswq.sql = prev
	}
	return nil
}

func (eswq *EmStockWatchQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EmStockWatch, error) {
	var (
		nodes = []*EmStockWatch{}
		_spec = eswq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EmStockWatch).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EmStockWatch{config: eswq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eswq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (eswq *EmStockWatchQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eswq.querySpec()
	_spec.Node.Columns = eswq.ctx.Fields
	if len(eswq.ctx.Fields) > 0 {
		_spec.Unique = eswq.ctx.Unique != nil && *eswq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eswq.driver, _spec)
}

func (eswq *EmStockWatchQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(emstockwatch.Table, emstockwatch.Columns, sqlgraph.NewFieldSpec(emstockwatch.FieldID, field.TypeInt32))
	_spec.From = eswq.sql
	if unique := eswq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eswq.path != nil {
		_spec.Unique = true
	}
	if fields := eswq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emstockwatch.FieldID)
		for i := range fields {
			if fields[i] != emstockwatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eswq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eswq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eswq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eswq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eswq *EmStockWatchQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eswq.driver.Dialect())
	t1 := builder.Table(emstockwatch.Table)
	columns := eswq.ctx.Fields
	if len(columns) == 0 {
		columns = emstockwatch.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eswq.sql != nil {
		selector = eswq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eswq.ctx.Unique != nil && *eswq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eswq.predicates {
		p(selector)
	}
	for _, p := range eswq.order {
		p(selector)
	}
	if offset := eswq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eswq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EmStockWatchGroupBy is the group-by builder for EmStockWatch entities.
type EmStockWatchGroupBy struct {
	selector
	build *EmStockWatchQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eswgb *EmStockWatchGroupBy) Aggregate(fns ...AggregateFunc) *EmStockWatchGroupBy {
	eswgb.fns = append(eswgb.fns, fns...)
	return eswgb
}

// Scan applies the selector query and scans the result into the given value.
func (eswgb *EmStockWatchGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eswgb.build.ctx, ent.OpQueryGroupBy)
	if err := eswgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmStockWatchQuery, *EmStockWatchGroupBy](ctx, eswgb.build, eswgb, eswgb.build.inters, v)
}

func (eswgb *EmStockWatchGroupBy) sqlScan(ctx context.Context, root *EmStockWatchQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eswgb.fns))
	for _, fn := range eswgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eswgb.flds)+len(eswgb.fns))
		for _, f := range *eswgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eswgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eswgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EmStockWatchSelect is the builder for selecting fields of EmStockWatch entities.
type EmStockWatchSelect struct {
	*EmStockWatchQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (esws *EmStockWatchSelect) Aggregate(fns ...AggregateFunc) *EmStockWatchSelect {
	esws.fns = append(esws.fns, fns...)
	return esws
}

// Scan applies the selector query and scans the result into the given value.
func (esws *EmStockWatchSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, esws.ctx, ent.OpQuerySelect)
	if err := esws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EmStockWatchQuery, *EmStockWatchSelect](ctx, esws.EmStockWatchQuery, esws, esws.inters, v)
}

func (esws *EmStockWatchSelect) sqlScan(ctx context.Context, root *EmStockWatchQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(esws.fns))
	for _, fn := range esws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*esws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := esws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
