// Code generated by ent, DO NOT EDIT.

package ent

import "time"

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdate) SetNotNilFinancialIndicatorsKey(value *string) *EmFinancialIndicatorUpdate {
	if value != nil {
		return efi.SetFinancialIndicatorsKey(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdateOne) SetNotNilFinancialIndicatorsKey(value *string) *EmFinancialIndicatorUpdateOne {
	if value != nil {
		return efi.SetFinancialIndicatorsKey(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorCreate) SetNotNilFinancialIndicatorsKey(value *string) *EmFinancialIndicatorCreate {
	if value != nil {
		return efi.SetFinancialIndicatorsKey(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdate) SetNotNilFinancialIndicatorsValue(value *string) *EmFinancialIndicatorUpdate {
	if value != nil {
		return efi.SetFinancialIndicatorsValue(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdateOne) SetNotNilFinancialIndicatorsValue(value *string) *EmFinancialIndicatorUpdateOne {
	if value != nil {
		return efi.SetFinancialIndicatorsValue(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorCreate) SetNotNilFinancialIndicatorsValue(value *string) *EmFinancialIndicatorCreate {
	if value != nil {
		return efi.SetFinancialIndicatorsValue(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdate) SetNotNilFinancialIndicatorsName(value *string) *EmFinancialIndicatorUpdate {
	if value != nil {
		return efi.SetFinancialIndicatorsName(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdateOne) SetNotNilFinancialIndicatorsName(value *string) *EmFinancialIndicatorUpdateOne {
	if value != nil {
		return efi.SetFinancialIndicatorsName(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorCreate) SetNotNilFinancialIndicatorsName(value *string) *EmFinancialIndicatorCreate {
	if value != nil {
		return efi.SetFinancialIndicatorsName(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdate) SetNotNilCreateTime(value *time.Time) *EmFinancialIndicatorUpdate {
	if value != nil {
		return efi.SetCreateTime(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdateOne) SetNotNilCreateTime(value *time.Time) *EmFinancialIndicatorUpdateOne {
	if value != nil {
		return efi.SetCreateTime(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorCreate) SetNotNilCreateTime(value *time.Time) *EmFinancialIndicatorCreate {
	if value != nil {
		return efi.SetCreateTime(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdate) SetNotNilRemarks(value *string) *EmFinancialIndicatorUpdate {
	if value != nil {
		return efi.SetRemarks(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdateOne) SetNotNilRemarks(value *string) *EmFinancialIndicatorUpdateOne {
	if value != nil {
		return efi.SetRemarks(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorCreate) SetNotNilRemarks(value *string) *EmFinancialIndicatorCreate {
	if value != nil {
		return efi.SetRemarks(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdate) SetNotNilStatus(value *string) *EmFinancialIndicatorUpdate {
	if value != nil {
		return efi.SetStatus(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorUpdateOne) SetNotNilStatus(value *string) *EmFinancialIndicatorUpdateOne {
	if value != nil {
		return efi.SetStatus(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (efi *EmFinancialIndicatorCreate) SetNotNilStatus(value *string) *EmFinancialIndicatorCreate {
	if value != nil {
		return efi.SetStatus(*value)
	}
	return efi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF1(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF1(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF1(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF1(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF1(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF1(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF2(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF2(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF2(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF2(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF2(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF2(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF3(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF3(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF3(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF3(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF3(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF3(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF4(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF4(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF4(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF4(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF4(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF4(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF5(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF5(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF5(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF5(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF5(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF5(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF6(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF6(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF6(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF6(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF6(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF6(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF7(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF7(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF7(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF7(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF7(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF7(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF8(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF8(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF8(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF8(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF8(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF8(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF9(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF9(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF9(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF9(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF9(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF9(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF10(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF10(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF10(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF10(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF10(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF10(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF11(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF11(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF11(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF11(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF11(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF11(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF12(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF12(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF12(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF12(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF12(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF12(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF13(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF13(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF13(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF13(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF13(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF13(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF14(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF14(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF14(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF14(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF14(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF14(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF15(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF15(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF15(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF15(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF15(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF15(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF16(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF16(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF16(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF16(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF16(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF16(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF17(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF17(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF17(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF17(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF17(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF17(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF18(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF18(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF18(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF18(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF18(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF18(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF19(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF19(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF19(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF19(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF19(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF19(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF20(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF20(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF20(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF20(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF20(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF20(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF21(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF21(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF21(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF21(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF21(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF21(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF22(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF22(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF22(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF22(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF22(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF22(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF23(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF23(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF23(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF23(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF23(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF23(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF24(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF24(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF24(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF24(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF24(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF24(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF25(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF25(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF25(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF25(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF25(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF25(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF26(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF26(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF26(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF26(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF26(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF26(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF27(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF27(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF27(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF27(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF27(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF27(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF28(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF28(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF28(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF28(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF28(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF28(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF29(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF29(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF29(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF29(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF29(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF29(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilF30(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetF30(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilF30(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetF30(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilF30(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetF30(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilCreateTime(value *time.Time) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetCreateTime(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilCreateTime(value *time.Time) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetCreateTime(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilCreateTime(value *time.Time) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetCreateTime(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilRemarks(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetRemarks(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilRemarks(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetRemarks(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilRemarks(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetRemarks(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilStatus(value *string) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetStatus(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilStatus(value *string) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetStatus(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilStatus(value *string) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetStatus(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilSt1(value *int32) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetSt1(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilSt1(value *int32) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetSt1(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilSt1(value *int32) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetSt1(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilSt2(value *int32) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetSt2(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilSt2(value *int32) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetSt2(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilSt2(value *int32) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetSt2(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilSt3(value *int32) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetSt3(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilSt3(value *int32) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetSt3(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilSt3(value *int32) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetSt3(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilSt4(value *int32) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetSt4(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilSt4(value *int32) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetSt4(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilSt4(value *int32) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetSt4(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdate) SetNotNilSt5(value *int32) *EmStockBasicInfoUpdate {
	if value != nil {
		return esbi.SetSt5(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoUpdateOne) SetNotNilSt5(value *int32) *EmStockBasicInfoUpdateOne {
	if value != nil {
		return esbi.SetSt5(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esbi *EmStockBasicInfoCreate) SetNotNilSt5(value *int32) *EmStockBasicInfoCreate {
	if value != nil {
		return esbi.SetSt5(*value)
	}
	return esbi
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdate) SetNotNilStockWatchCode(value *string) *EmStockWatchUpdate {
	if value != nil {
		return esw.SetStockWatchCode(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdateOne) SetNotNilStockWatchCode(value *string) *EmStockWatchUpdateOne {
	if value != nil {
		return esw.SetStockWatchCode(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchCreate) SetNotNilStockWatchCode(value *string) *EmStockWatchCreate {
	if value != nil {
		return esw.SetStockWatchCode(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdate) SetNotNilStockWatchName(value *string) *EmStockWatchUpdate {
	if value != nil {
		return esw.SetStockWatchName(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdateOne) SetNotNilStockWatchName(value *string) *EmStockWatchUpdateOne {
	if value != nil {
		return esw.SetStockWatchName(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchCreate) SetNotNilStockWatchName(value *string) *EmStockWatchCreate {
	if value != nil {
		return esw.SetStockWatchName(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdate) SetNotNilStockWatchUpPrice(value *string) *EmStockWatchUpdate {
	if value != nil {
		return esw.SetStockWatchUpPrice(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdateOne) SetNotNilStockWatchUpPrice(value *string) *EmStockWatchUpdateOne {
	if value != nil {
		return esw.SetStockWatchUpPrice(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchCreate) SetNotNilStockWatchUpPrice(value *string) *EmStockWatchCreate {
	if value != nil {
		return esw.SetStockWatchUpPrice(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdate) SetNotNilStockWatchFallPrice(value *string) *EmStockWatchUpdate {
	if value != nil {
		return esw.SetStockWatchFallPrice(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdateOne) SetNotNilStockWatchFallPrice(value *string) *EmStockWatchUpdateOne {
	if value != nil {
		return esw.SetStockWatchFallPrice(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchCreate) SetNotNilStockWatchFallPrice(value *string) *EmStockWatchCreate {
	if value != nil {
		return esw.SetStockWatchFallPrice(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdate) SetNotNilStockWatchUpChange(value *string) *EmStockWatchUpdate {
	if value != nil {
		return esw.SetStockWatchUpChange(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdateOne) SetNotNilStockWatchUpChange(value *string) *EmStockWatchUpdateOne {
	if value != nil {
		return esw.SetStockWatchUpChange(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchCreate) SetNotNilStockWatchUpChange(value *string) *EmStockWatchCreate {
	if value != nil {
		return esw.SetStockWatchUpChange(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdate) SetNotNilStockWatchFallChange(value *string) *EmStockWatchUpdate {
	if value != nil {
		return esw.SetStockWatchFallChange(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchUpdateOne) SetNotNilStockWatchFallChange(value *string) *EmStockWatchUpdateOne {
	if value != nil {
		return esw.SetStockWatchFallChange(*value)
	}
	return esw
}

// set field if value's pointer is not nil.
func (esw *EmStockWatchCreate) SetNotNilStockWatchFallChange(value *string) *EmStockWatchCreate {
	if value != nil {
		return esw.SetStockWatchFallChange(*value)
	}
	return esw
}
