// Code generated by goctl. DO NOT EDIT.
package types

// The basic response with data | 基础带数据信息
// swagger:model BaseDataInfo
type BaseDataInfo struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
	// Data | 数据
	Data string `json:"data,omitempty"`
}

// The basic response with data | 基础带数据信息
// swagger:model BaseListInfo
type BaseListInfo struct {
	// The total number of data | 数据总数
	Total uint64 `json:"total"`
	// Data | 数据
	Data string `json:"data,omitempty"`
}

// The basic response without data | 基础不带数据信息
// swagger:model BaseMsgResp
type BaseMsgResp struct {
	// Error code | 错误代码
	Code int `json:"code"`
	// Message | 提示信息
	Msg string `json:"msg"`
}

// The page request parameters | 列表请求参数
// swagger:model PageInfo
type PageInfo struct {
	// Page number | 第几页
	// required : true
	// min : 0
	Page uint64 `json:"page" validate:"required,number,gt=0"`
	// Page size | 单页数据行数
	// required : true
	// max : 100000
	PageSize uint64 `json:"pageSize" validate:"required,number,lt=100000"`
}

// Basic ID request | 基础ID参数请求
// swagger:model IDReq
type IDReq struct {
	// ID
	// Required: true
	Id uint64 `json:"id" validate:"number"`
}

// Basic IDs request | 基础ID数组参数请求
// swagger:model IDsReq
type IDsReq struct {
	// IDs
	// Required: true
	Ids []uint64 `json:"ids"`
}

// Basic ID request | 基础ID地址参数请求
// swagger:model IDPathReq
type IDPathReq struct {
	// ID
	// Required: true
	Id uint64 `path:"id"`
}

// Basic ID request (int32) | 基础ID参数请求 (int32)
// swagger:model IDInt32Req
type IDInt32Req struct {
	// ID
	// Required: true
	Id int32 `json:"id" validate:"number"`
}

// Basic IDs request (int32) | 基础ID数组参数请求 (int32)
// swagger:model IDsInt32Req
type IDsInt32Req struct {
	// IDs
	// Required: true
	Ids []int32 `json:"ids"`
}

// Basic ID request (int32) | 基础ID地址参数请求 (int32)
// swagger:model IDInt32PathReq
type IDInt32PathReq struct {
	// ID
	// Required: true
	Id int32 `path:"id"`
}

// Basic ID request (uint32) | 基础ID参数请求 (uint32)
// swagger:model IDUint32Req
type IDUint32Req struct {
	// ID
	// Required: true
	Id uint32 `json:"id" validate:"number"`
}

// Basic IDs request (uint32) | 基础ID数组参数请求 (uint32)
// swagger:model IDsUint32Req
type IDsUint32Req struct {
	// IDs
	// Required: true
	Ids []uint32 `json:"ids"`
}

// Basic ID request (uint32) | 基础ID地址参数请求 (uint32)
// swagger:model IDUint32PathReq
type IDUint32PathReq struct {
	// ID
	// Required: true
	Id uint32 `path:"id"`
}

// Basic ID request (int64) | 基础ID参数请求 (int64)
// swagger:model IDInt64Req
type IDInt64Req struct {
	// ID
	// Required: true
	Id int64 `json:"id" validate:"number"`
}

// Basic IDs request (int64) | 基础ID数组参数请求 (int64)
// swagger:model IDsInt64Req
type IDsInt64Req struct {
	// IDs
	// Required: true
	Ids []int64 `json:"ids"`
}

// Basic ID request (int64) | 基础ID地址参数请求 (int64)
// swagger:model IDInt64PathReq
type IDInt64PathReq struct {
	// ID
	// Required: true
	Id int64 `path:"id"`
}

// Basic ID request (string) | 基础ID参数请求 (string)
// swagger:model IDStringReq
type IDStringReq struct {
	// ID
	// Required: true
	Id string `json:"id"`
}

// Basic IDs request (string) | 基础ID数组参数请求 (string)
// swagger:model IDsStringReq
type IDsStringReq struct {
	// IDs
	// Required: true
	Ids []string `json:"ids"`
}

// Basic ID request (string) | 基础ID地址参数请求 (string)
// swagger:model IDStringPathReq
type IDStringPathReq struct {
	// ID
	// Required: true
	Id string `path:"id"`
}

// Basic UUID request in path | 基础UUID地址参数请求
// swagger:model UUIDPathReq
type UUIDPathReq struct {
	// ID
	// Required: true
	Id string `path:"id"`
}

// Basic UUID request | 基础UUID参数请求
// swagger:model UUIDReq
type UUIDReq struct {
	// ID
	// required : true
	// max length : 36
	// min length : 36
	Id string `json:"id" validate:"required,len=36"`
}

// Basic UUID array request | 基础UUID数组参数请求
// swagger:model UUIDsReq
type UUIDsReq struct {
	// Ids
	// Required: true
	Ids []string `json:"ids"`
}

// The base ID response data | 基础ID信息
// swagger:model BaseIDInfo
type BaseIDInfo struct {
	// ID
	Id *uint64 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base ID response data (int64) | 基础ID信息 (int64)
// swagger:model BaseIDInt64Info
type BaseIDInt64Info struct {
	// ID
	Id *int64 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base ID response data (int32) | 基础ID信息 (int32)
// swagger:model BaseIDInt32Info
type BaseIDInt32Info struct {
	// ID
	Id *int32 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base ID response data (uint32) | 基础ID信息 (uint32)
// swagger:model BaseIDUint32Info
type BaseIDUint32Info struct {
	// ID
	Id *uint32 `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base UUID response data | 基础UUID信息
// swagger:model BaseUUIDInfo
type BaseUUIDInfo struct {
	// ID
	Id *string `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The base ID response data (string) | 基础ID信息 (string)
// swagger:model BaseIDStringInfo
type BaseIDStringInfo struct {
	// ID
	Id *string `json:"id,optional"`
	// Create date | 创建日期
	CreatedAt *int64 `json:"createdAt,optional"`
	// Update date | 更新日期
	UpdatedAt *int64 `json:"updatedAt,optional"`
}

// The response data of em financial indicator information | EmFinancialIndicator信息
// swagger:model EmFinancialIndicatorInfo
type EmFinancialIndicatorInfo struct {
	Id *int32 `json:"id,optional"`
	// FinancialIndicatorsKey
	FinancialIndicatorsKey *string `json:"financialIndicatorsKey,optional"`
	// FinancialIndicatorsValue
	FinancialIndicatorsValue *string `json:"financialIndicatorsValue,optional"`
	// FinancialIndicatorsName
	FinancialIndicatorsName *string `json:"financialIndicatorsName,optional"`
	// CreateTime
	CreateTime *int64 `json:"createTime,optional"`
	// Remarks
	Remarks *string `json:"remarks,optional"`
	// Status
	Status *string `json:"status,optional"`
}

// The response data of em financial indicator list | EmFinancialIndicator信息列表数据
// swagger:model EmFinancialIndicatorListResp
type EmFinancialIndicatorListResp struct {
	BaseDataInfo
	// EmFinancialIndicator list data | EmFinancialIndicator信息列表数据
	Data EmFinancialIndicatorListInfo `json:"data"`
}

// The em financial indicator list data | EmFinancialIndicator信息列表数据
// swagger:model EmFinancialIndicatorListInfo
type EmFinancialIndicatorListInfo struct {
	BaseListInfo
	// The em financial indicator list data | EmFinancialIndicator信息列表数据
	Data []EmFinancialIndicatorInfo `json:"data"`
}

// Get em financial indicator list request params | EmFinancialIndicator列表请求参数
// swagger:model EmFinancialIndicatorListReq
type EmFinancialIndicatorListReq struct {
	PageInfo
	// FinancialIndicatorsKey
	FinancialIndicatorsKey *string `json:"financialIndicatorsKey,optional"`
	// FinancialIndicatorsValue
	FinancialIndicatorsValue *string `json:"financialIndicatorsValue,optional"`
	// FinancialIndicatorsName
	FinancialIndicatorsName *string `json:"financialIndicatorsName,optional"`
}

// The em financial indicator information response | EmFinancialIndicator信息返回体
// swagger:model EmFinancialIndicatorInfoResp
type EmFinancialIndicatorInfoResp struct {
	BaseDataInfo
	// The em financial indicator information | EmFinancialIndicator信息数据
	Data EmFinancialIndicatorInfo `json:"data"`
}

// The response data of em stock basic info information | EmStockBasicInfo信息
// swagger:model EmStockBasicInfoInfo
type EmStockBasicInfoInfo struct {
	Id *int32 `json:"id,optional"`
	// F1
	F1 *string `json:"f1,optional"`
	// F2
	F2 *string `json:"f2,optional"`
	// F3
	F3 *string `json:"f3,optional"`
	// F4
	F4 *string `json:"f4,optional"`
	// F5
	F5 *string `json:"f5,optional"`
	// F6
	F6 *string `json:"f6,optional"`
	// F7
	F7 *string `json:"f7,optional"`
	// F8
	F8 *string `json:"f8,optional"`
	// F9
	F9 *string `json:"f9,optional"`
	// F10
	F10 *string `json:"f10,optional"`
	// F11
	F11 *string `json:"f11,optional"`
	// F12
	F12 *string `json:"f12,optional"`
	// F13
	F13 *string `json:"f13,optional"`
	// F14
	F14 *string `json:"f14,optional"`
	// F15
	F15 *string `json:"f15,optional"`
	// F16
	F16 *string `json:"f16,optional"`
	// F17
	F17 *string `json:"f17,optional"`
	// F18
	F18 *string `json:"f18,optional"`
	// F19
	F19 *string `json:"f19,optional"`
	// F20
	F20 *string `json:"f20,optional"`
	// F21
	F21 *string `json:"f21,optional"`
	// F22
	F22 *string `json:"f22,optional"`
	// F23
	F23 *string `json:"f23,optional"`
	// F24
	F24 *string `json:"f24,optional"`
	// F25
	F25 *string `json:"f25,optional"`
	// F26
	F26 *string `json:"f26,optional"`
	// F27
	F27 *string `json:"f27,optional"`
	// F28
	F28 *string `json:"f28,optional"`
	// F29
	F29 *string `json:"f29,optional"`
	// F30
	F30 *string `json:"f30,optional"`
	// CreateTime
	CreateTime *int64 `json:"createTime,optional"`
	// Remarks
	Remarks *string `json:"remarks,optional"`
	// Status
	Status *string `json:"status,optional"`
	// St1
	St1 *int32 `json:"st1,optional"`
	// St2
	St2 *int32 `json:"st2,optional"`
	// St3
	St3 *int32 `json:"st3,optional"`
	// St4
	St4 *int32 `json:"st4,optional"`
	// St5
	St5 *int32 `json:"st5,optional"`
}

// The response data of em stock basic info list | EmStockBasicInfo信息列表数据
// swagger:model EmStockBasicInfoListResp
type EmStockBasicInfoListResp struct {
	BaseDataInfo
	// EmStockBasicInfo list data | EmStockBasicInfo信息列表数据
	Data EmStockBasicInfoListInfo `json:"data"`
}

// The em stock basic info list data | EmStockBasicInfo信息列表数据
// swagger:model EmStockBasicInfoListInfo
type EmStockBasicInfoListInfo struct {
	BaseListInfo
	// The em stock basic info list data | EmStockBasicInfo信息列表数据
	Data []EmStockBasicInfoInfo `json:"data"`
}

// Get em stock basic info list request params | EmStockBasicInfo列表请求参数
// swagger:model EmStockBasicInfoListReq
type EmStockBasicInfoListReq struct {
	PageInfo
}

// The em stock basic info information response | EmStockBasicInfo信息返回体
// swagger:model EmStockBasicInfoInfoResp
type EmStockBasicInfoInfoResp struct {
	BaseDataInfo
	// The em stock basic info information | EmStockBasicInfo信息数据
	Data EmStockBasicInfoInfo `json:"data"`
}

// The response data of em stock watch information | EmStockWatch信息
// swagger:model EmStockWatchInfo
type EmStockWatchInfo struct {
	Id *int32 `json:"id,optional"`
	// StockWatchCode
	StockWatchCode *string `json:"stockWatchCode,optional"`
	// StockWatchName
	StockWatchName *string `json:"stockWatchName,optional"`
	// StockWatchUpPrice
	StockWatchUpPrice *string `json:"stockWatchUpPrice,optional"`
	// StockWatchFallPrice
	StockWatchFallPrice *string `json:"stockWatchFallPrice,optional"`
	// StockWatchUpChange
	StockWatchUpChange *string `json:"stockWatchUpChange,optional"`
	// StockWatchFallChange
	StockWatchFallChange *string `json:"stockWatchFallChange,optional"`
}

// The response data of em stock watch list | EmStockWatch信息列表数据
// swagger:model EmStockWatchListResp
type EmStockWatchListResp struct {
	BaseDataInfo
	// EmStockWatch list data | EmStockWatch信息列表数据
	Data EmStockWatchListInfo `json:"data"`
}

// The em stock watch list data | EmStockWatch信息列表数据
// swagger:model EmStockWatchListInfo
type EmStockWatchListInfo struct {
	BaseListInfo
	// The em stock watch list data | EmStockWatch信息列表数据
	Data []EmStockWatchInfo `json:"data"`
}

// Get em stock watch list request params | EmStockWatch列表请求参数
// swagger:model EmStockWatchListReq
type EmStockWatchListReq struct {
	PageInfo
	// StockWatchCode
	StockWatchCode *string `json:"stockWatchCode,optional"`
	// StockWatchName
	StockWatchName *string `json:"stockWatchName,optional"`
	// StockWatchUpPrice
	StockWatchUpPrice *string `json:"stockWatchUpPrice,optional"`
}

// The em stock watch information response | EmStockWatch信息返回体
// swagger:model EmStockWatchInfoResp
type EmStockWatchInfoResp struct {
	BaseDataInfo
	// The em stock watch information | EmStockWatch信息数据
	Data EmStockWatchInfo `json:"data"`
}
