// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EmFinancialIndicatorsColumns holds the columns for the "em_financial_indicators" table.
	EmFinancialIndicatorsColumns = []*schema.Column{
		{Name: "financial_indicators_id", Type: field.TypeInt32, Increment: true},
		{Name: "financial_indicators_key", Type: field.TypeString, Nullable: true},
		{Name: "financial_indicators_value", Type: field.TypeString, Nullable: true},
		{Name: "financial_indicators_name", Type: field.TypeString, Nullable: true},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "remarks", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Nullable: true},
	}
	// EmFinancialIndicatorsTable holds the schema information for the "em_financial_indicators" table.
	EmFinancialIndicatorsTable = &schema.Table{
		Name:       "em_financial_indicator",
		Columns:    EmFinancialIndicatorsColumns,
		PrimaryKey: []*schema.Column{EmFinancialIndicatorsColumns[0]},
	}
	// EmStockBasicInfosColumns holds the columns for the "em_stock_basic_infos" table.
	EmStockBasicInfosColumns = []*schema.Column{
		{Name: "stock_basic_info_id", Type: field.TypeInt32, Increment: true},
		{Name: "f1", Type: field.TypeString, Nullable: true},
		{Name: "f2", Type: field.TypeString, Nullable: true},
		{Name: "f3", Type: field.TypeString, Nullable: true},
		{Name: "f4", Type: field.TypeString, Nullable: true},
		{Name: "f5", Type: field.TypeString, Nullable: true},
		{Name: "f6", Type: field.TypeString, Nullable: true},
		{Name: "f7", Type: field.TypeString, Nullable: true},
		{Name: "f8", Type: field.TypeString, Nullable: true},
		{Name: "f9", Type: field.TypeString, Nullable: true},
		{Name: "f10", Type: field.TypeString, Nullable: true},
		{Name: "f11", Type: field.TypeString, Nullable: true},
		{Name: "f12", Type: field.TypeString, Nullable: true},
		{Name: "f13", Type: field.TypeString, Nullable: true},
		{Name: "f14", Type: field.TypeString, Nullable: true},
		{Name: "f15", Type: field.TypeString, Nullable: true},
		{Name: "f16", Type: field.TypeString, Nullable: true},
		{Name: "f17", Type: field.TypeString, Nullable: true},
		{Name: "f18", Type: field.TypeString, Nullable: true},
		{Name: "f19", Type: field.TypeString, Nullable: true},
		{Name: "f20", Type: field.TypeString, Nullable: true},
		{Name: "f21", Type: field.TypeString, Nullable: true},
		{Name: "f22", Type: field.TypeString, Nullable: true},
		{Name: "f23", Type: field.TypeString, Nullable: true},
		{Name: "f24", Type: field.TypeString, Nullable: true},
		{Name: "f25", Type: field.TypeString, Nullable: true},
		{Name: "f26", Type: field.TypeString, Nullable: true},
		{Name: "f27", Type: field.TypeString, Nullable: true},
		{Name: "f28", Type: field.TypeString, Nullable: true},
		{Name: "f29", Type: field.TypeString, Nullable: true},
		{Name: "f30", Type: field.TypeString, Nullable: true},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "remarks", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Nullable: true},
		{Name: "st1", Type: field.TypeInt32, Nullable: true},
		{Name: "st2", Type: field.TypeInt32, Nullable: true},
		{Name: "st3", Type: field.TypeInt32, Nullable: true},
		{Name: "st4", Type: field.TypeInt32, Nullable: true},
		{Name: "st5", Type: field.TypeInt32, Nullable: true},
	}
	// EmStockBasicInfosTable holds the schema information for the "em_stock_basic_infos" table.
	EmStockBasicInfosTable = &schema.Table{
		Name:       "em_stock_basic_info",
		Columns:    EmStockBasicInfosColumns,
		PrimaryKey: []*schema.Column{EmStockBasicInfosColumns[0]},
	}
	// EmStockWatchsColumns holds the columns for the "em_stock_watchs" table.
	EmStockWatchsColumns = []*schema.Column{
		{Name: "stock_watch_id", Type: field.TypeInt32, Increment: true},
		{Name: "stock_watch_code", Type: field.TypeString, Nullable: true},
		{Name: "stock_watch_name", Type: field.TypeString, Nullable: true},
		{Name: "stock_watch_up_price", Type: field.TypeString, Nullable: true},
		{Name: "stock_watch_fall_price", Type: field.TypeString, Nullable: true},
		{Name: "stock_watch_up_change", Type: field.TypeString, Nullable: true},
		{Name: "stock_watch_fall_change", Type: field.TypeString, Nullable: true},
	}
	// EmStockWatchsTable holds the schema information for the "em_stock_watchs" table.
	EmStockWatchsTable = &schema.Table{
		Name:       "em_stock_watch",
		Columns:    EmStockWatchsColumns,
		PrimaryKey: []*schema.Column{EmStockWatchsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EmFinancialIndicatorsTable,
		EmStockBasicInfosTable,
		EmStockWatchsTable,
	}
)

func init() {
	EmFinancialIndicatorsTable.Annotation = &entsql.Annotation{
		Table: "em_financial_indicator",
	}
	EmStockBasicInfosTable.Annotation = &entsql.Annotation{
		Table: "em_stock_basic_info",
	}
	EmStockWatchsTable.Annotation = &entsql.Annotation{
		Table: "em_stock_watch",
	}
}
